name: example
description: A new Flutter application.

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  crypto_stream:
    path: ..
  path_provider: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
