name: example
description: A new Flutter application.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  crypto_stream:
    path: ..
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
