name: crypto_stream
description: A new flutter plugin project.
version: 0.0.3

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.afterlogic.crypto_stream
        pluginClass: crypto_stream
      ios:
        pluginClass: crypto_stream
