//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/asn1/cmc/Asn1CmcUtils.java
//

#ifndef Asn1CmcUtils_H
#define Asn1CmcUtils_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@class IOSObjectArray;
@class LibOrgBouncycastleAsn1ASN1Sequence;

@interface LibOrgBouncycastleAsn1CmcAsn1CmcUtils : NSObject

#pragma mark Package-Private

- (instancetype __nonnull)init;

+ (IOSObjectArray *)cloneWithLibOrgBouncycastleAsn1CmcBodyPartIDArray:(IOSObjectArray *)ids;

+ (IOSObjectArray *)cloneWithLibOrgBouncycastleAsn1X509ExtensionArray:(IOSObjectArray *)ids;

+ (IOSObjectArray *)toBodyPartIDArrayWithLibOrgBouncycastleAsn1ASN1Sequence:(LibOrgBouncycastleAsn1ASN1Sequence *)bodyPartIDs;

@end

J2OBJC_EMPTY_STATIC_INIT(LibOrgBouncycastleAsn1CmcAsn1CmcUtils)

FOUNDATION_EXPORT void LibOrgBouncycastleAsn1CmcAsn1CmcUtils_init(LibOrgBouncycastleAsn1CmcAsn1CmcUtils *self);

FOUNDATION_EXPORT LibOrgBouncycastleAsn1CmcAsn1CmcUtils *new_LibOrgBouncycastleAsn1CmcAsn1CmcUtils_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT LibOrgBouncycastleAsn1CmcAsn1CmcUtils *create_LibOrgBouncycastleAsn1CmcAsn1CmcUtils_init(void);

FOUNDATION_EXPORT IOSObjectArray *LibOrgBouncycastleAsn1CmcAsn1CmcUtils_toBodyPartIDArrayWithLibOrgBouncycastleAsn1ASN1Sequence_(LibOrgBouncycastleAsn1ASN1Sequence *bodyPartIDs);

FOUNDATION_EXPORT IOSObjectArray *LibOrgBouncycastleAsn1CmcAsn1CmcUtils_cloneWithLibOrgBouncycastleAsn1CmcBodyPartIDArray_(IOSObjectArray *ids);

FOUNDATION_EXPORT IOSObjectArray *LibOrgBouncycastleAsn1CmcAsn1CmcUtils_cloneWithLibOrgBouncycastleAsn1X509ExtensionArray_(IOSObjectArray *ids);

J2OBJC_TYPE_LITERAL_HEADER(LibOrgBouncycastleAsn1CmcAsn1CmcUtils)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // Asn1CmcUtils_H
