//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/pqc/jcajce/provider/rainbow/BCRainbowPrivateKey.java
//

#include "ASN1ObjectIdentifier.h"
#include "AlgorithmIdentifier.h"
#include "Arrays.h"
#include "BCRainbowPrivateKey.h"
#include "DERNull.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "Layer.h"
#include "PQCObjectIdentifiers.h"
#include "PrivateKeyInfo.h"
#include "RainbowPrivateKey.h"
#include "RainbowPrivateKeyParameters.h"
#include "RainbowPrivateKeySpec.h"
#include "RainbowUtil.h"
#include "java/io/IOException.h"
#include "java/util/Arrays.h"
#include "javax/security/auth/Destroyable.h"

@interface LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey () {
 @public
  IOSObjectArray *A1inv_;
  IOSShortArray *b1_;
  IOSObjectArray *A2inv_;
  IOSShortArray *b2_;
  IOSObjectArray *layers_;
  IOSIntArray *vi_;
}

@end

J2OBJC_FIELD_SETTER(LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey, A1inv_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey, b1_, IOSShortArray *)
J2OBJC_FIELD_SETTER(LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey, A2inv_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey, b2_, IOSShortArray *)
J2OBJC_FIELD_SETTER(LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey, layers_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey, vi_, IOSIntArray *)

inline jlong LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey_get_serialVersionUID(void);
#define LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey_serialVersionUID 1LL
J2OBJC_STATIC_FIELD_CONSTANT(LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey, serialVersionUID, jlong)

@implementation LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey

- (instancetype)initWithShortArray2:(IOSObjectArray *)A1inv
                     withShortArray:(IOSShortArray *)b1
                    withShortArray2:(IOSObjectArray *)A2inv
                     withShortArray:(IOSShortArray *)b2
                       withIntArray:(IOSIntArray *)vi
withLibOrgBouncycastlePqcCryptoRainbowLayerArray:(IOSObjectArray *)layers {
  LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey_initWithShortArray2_withShortArray_withShortArray2_withShortArray_withIntArray_withLibOrgBouncycastlePqcCryptoRainbowLayerArray_(self, A1inv, b1, A2inv, b2, vi, layers);
  return self;
}

- (instancetype)initWithLibOrgBouncycastlePqcJcajceSpecRainbowPrivateKeySpec:(LibOrgBouncycastlePqcJcajceSpecRainbowPrivateKeySpec *)keySpec {
  LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey_initWithLibOrgBouncycastlePqcJcajceSpecRainbowPrivateKeySpec_(self, keySpec);
  return self;
}

- (instancetype)initWithLibOrgBouncycastlePqcCryptoRainbowRainbowPrivateKeyParameters:(LibOrgBouncycastlePqcCryptoRainbowRainbowPrivateKeyParameters *)params {
  LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey_initWithLibOrgBouncycastlePqcCryptoRainbowRainbowPrivateKeyParameters_(self, params);
  return self;
}

- (IOSObjectArray *)getInvA1 {
  return self->A1inv_;
}

- (IOSShortArray *)getB1 {
  return self->b1_;
}

- (IOSShortArray *)getB2 {
  return self->b2_;
}

- (IOSObjectArray *)getInvA2 {
  return self->A2inv_;
}

- (IOSObjectArray *)getLayers {
  return self->layers_;
}

- (IOSIntArray *)getVi {
  return vi_;
}

- (jboolean)isEqual:(id)other {
  if (other == nil || !([other isKindOfClass:[LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey class]])) {
    return false;
  }
  LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey *otherKey = (LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey *) cast_chk(other, [LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey class]);
  jboolean eq = true;
  eq = (eq && LibOrgBouncycastlePqcCryptoRainbowUtilRainbowUtil_equalsWithShortArray2_withShortArray2_(A1inv_, [otherKey getInvA1]));
  eq = (eq && LibOrgBouncycastlePqcCryptoRainbowUtilRainbowUtil_equalsWithShortArray2_withShortArray2_(A2inv_, [otherKey getInvA2]));
  eq = (eq && LibOrgBouncycastlePqcCryptoRainbowUtilRainbowUtil_equalsWithShortArray_withShortArray_(b1_, [otherKey getB1]));
  eq = (eq && LibOrgBouncycastlePqcCryptoRainbowUtilRainbowUtil_equalsWithShortArray_withShortArray_(b2_, [otherKey getB2]));
  eq = (eq && JavaUtilArrays_equalsWithIntArray_withIntArray_(vi_, [otherKey getVi]));
  if (((IOSObjectArray *) nil_chk(layers_))->size_ != ((IOSObjectArray *) nil_chk([otherKey getLayers]))->size_) {
    return false;
  }
  for (jint i = ((IOSObjectArray *) nil_chk(layers_))->size_ - 1; i >= 0; i--) {
    eq &= [((LibOrgBouncycastlePqcCryptoRainbowLayer *) nil_chk(IOSObjectArray_Get(nil_chk(layers_), i))) isEqual:IOSObjectArray_Get(nil_chk([otherKey getLayers]), i)];
  }
  return eq;
}

- (NSUInteger)hash {
  jint hash_ = ((IOSObjectArray *) nil_chk(layers_))->size_;
  hash_ = hash_ * 37 + LibOrgBouncycastleUtilArrays_hashCodeWithShortArray2_(A1inv_);
  hash_ = hash_ * 37 + LibOrgBouncycastleUtilArrays_hashCodeWithShortArray_(b1_);
  hash_ = hash_ * 37 + LibOrgBouncycastleUtilArrays_hashCodeWithShortArray2_(A2inv_);
  hash_ = hash_ * 37 + LibOrgBouncycastleUtilArrays_hashCodeWithShortArray_(b2_);
  hash_ = hash_ * 37 + LibOrgBouncycastleUtilArrays_hashCodeWithIntArray_(vi_);
  for (jint i = ((IOSObjectArray *) nil_chk(layers_))->size_ - 1; i >= 0; i--) {
    hash_ = hash_ * 37 + ((jint) [((LibOrgBouncycastlePqcCryptoRainbowLayer *) nil_chk(IOSObjectArray_Get(nil_chk(layers_), i))) hash]);
  }
  return hash_;
}

- (NSString *)getAlgorithm {
  return @"Rainbow";
}

- (IOSByteArray *)getEncoded {
  LibOrgBouncycastlePqcAsn1RainbowPrivateKey *privateKey = new_LibOrgBouncycastlePqcAsn1RainbowPrivateKey_initWithShortArray2_withShortArray_withShortArray2_withShortArray_withIntArray_withLibOrgBouncycastlePqcCryptoRainbowLayerArray_(A1inv_, b1_, A2inv_, b2_, vi_, layers_);
  LibOrgBouncycastleAsn1PkcsPrivateKeyInfo *pki;
  @try {
    LibOrgBouncycastleAsn1X509AlgorithmIdentifier *algorithmIdentifier = new_LibOrgBouncycastleAsn1X509AlgorithmIdentifier_initWithLibOrgBouncycastleAsn1ASN1ObjectIdentifier_withLibOrgBouncycastleAsn1ASN1Encodable_(JreLoadStatic(LibOrgBouncycastlePqcAsn1PQCObjectIdentifiers, rainbow), JreLoadStatic(LibOrgBouncycastleAsn1DERNull, INSTANCE));
    pki = new_LibOrgBouncycastleAsn1PkcsPrivateKeyInfo_initWithLibOrgBouncycastleAsn1X509AlgorithmIdentifier_withLibOrgBouncycastleAsn1ASN1Encodable_(algorithmIdentifier, privateKey);
  }
  @catch (JavaIoIOException *e) {
    return nil;
  }
  @try {
    IOSByteArray *encoded = [((LibOrgBouncycastleAsn1PkcsPrivateKeyInfo *) nil_chk(pki)) getEncoded];
    return encoded;
  }
  @catch (JavaIoIOException *e) {
    return nil;
  }
}

- (NSString *)getFormat {
  return @"PKCS#8";
}

- (void)destroy {
  JavaxSecurityAuthDestroyable_destroy(self);
}

- (jboolean)isDestroyed {
  return JavaxSecurityAuthDestroyable_isDestroyed(self);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, "[[S", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[S", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[S", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[[S", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[LLibOrgBouncycastlePqcCryptoRainbowLayer;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 5, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x11, -1, -1, -1, -1, -1, -1 },
    { NULL, "[B", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithShortArray2:withShortArray:withShortArray2:withShortArray:withIntArray:withLibOrgBouncycastlePqcCryptoRainbowLayerArray:);
  methods[1].selector = @selector(initWithLibOrgBouncycastlePqcJcajceSpecRainbowPrivateKeySpec:);
  methods[2].selector = @selector(initWithLibOrgBouncycastlePqcCryptoRainbowRainbowPrivateKeyParameters:);
  methods[3].selector = @selector(getInvA1);
  methods[4].selector = @selector(getB1);
  methods[5].selector = @selector(getB2);
  methods[6].selector = @selector(getInvA2);
  methods[7].selector = @selector(getLayers);
  methods[8].selector = @selector(getVi);
  methods[9].selector = @selector(isEqual:);
  methods[10].selector = @selector(hash);
  methods[11].selector = @selector(getAlgorithm);
  methods[12].selector = @selector(getEncoded);
  methods[13].selector = @selector(getFormat);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "J", .constantValue.asLong = LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey_serialVersionUID, 0x1a, -1, -1, -1, -1 },
    { "A1inv_", "[[S", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "b1_", "[S", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "A2inv_", "[[S", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "b2_", "[S", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "layers_", "[LLibOrgBouncycastlePqcCryptoRainbowLayer;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "vi_", "[I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "[[S[S[[S[S[I[LLibOrgBouncycastlePqcCryptoRainbowLayer;", "LLibOrgBouncycastlePqcJcajceSpecRainbowPrivateKeySpec;", "LLibOrgBouncycastlePqcCryptoRainbowRainbowPrivateKeyParameters;", "equals", "LNSObject;", "hashCode" };
  static const J2ObjcClassInfo _LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey = { "BCRainbowPrivateKey", "lib.org.bouncycastle.pqc.jcajce.provider.rainbow", ptrTable, methods, fields, 7, 0x1, 14, 7, -1, -1, -1, -1, -1 };
  return &_LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey;
}

@end

void LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey_initWithShortArray2_withShortArray_withShortArray2_withShortArray_withIntArray_withLibOrgBouncycastlePqcCryptoRainbowLayerArray_(LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey *self, IOSObjectArray *A1inv, IOSShortArray *b1, IOSObjectArray *A2inv, IOSShortArray *b2, IOSIntArray *vi, IOSObjectArray *layers) {
  NSObject_init(self);
  self->A1inv_ = A1inv;
  self->b1_ = b1;
  self->A2inv_ = A2inv;
  self->b2_ = b2;
  self->vi_ = vi;
  self->layers_ = layers;
}

LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey *new_LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey_initWithShortArray2_withShortArray_withShortArray2_withShortArray_withIntArray_withLibOrgBouncycastlePqcCryptoRainbowLayerArray_(IOSObjectArray *A1inv, IOSShortArray *b1, IOSObjectArray *A2inv, IOSShortArray *b2, IOSIntArray *vi, IOSObjectArray *layers) {
  J2OBJC_NEW_IMPL(LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey, initWithShortArray2_withShortArray_withShortArray2_withShortArray_withIntArray_withLibOrgBouncycastlePqcCryptoRainbowLayerArray_, A1inv, b1, A2inv, b2, vi, layers)
}

LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey *create_LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey_initWithShortArray2_withShortArray_withShortArray2_withShortArray_withIntArray_withLibOrgBouncycastlePqcCryptoRainbowLayerArray_(IOSObjectArray *A1inv, IOSShortArray *b1, IOSObjectArray *A2inv, IOSShortArray *b2, IOSIntArray *vi, IOSObjectArray *layers) {
  J2OBJC_CREATE_IMPL(LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey, initWithShortArray2_withShortArray_withShortArray2_withShortArray_withIntArray_withLibOrgBouncycastlePqcCryptoRainbowLayerArray_, A1inv, b1, A2inv, b2, vi, layers)
}

void LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey_initWithLibOrgBouncycastlePqcJcajceSpecRainbowPrivateKeySpec_(LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey *self, LibOrgBouncycastlePqcJcajceSpecRainbowPrivateKeySpec *keySpec) {
  LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey_initWithShortArray2_withShortArray_withShortArray2_withShortArray_withIntArray_withLibOrgBouncycastlePqcCryptoRainbowLayerArray_(self, [((LibOrgBouncycastlePqcJcajceSpecRainbowPrivateKeySpec *) nil_chk(keySpec)) getInvA1], [keySpec getB1], [keySpec getInvA2], [keySpec getB2], [keySpec getVi], [keySpec getLayers]);
}

LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey *new_LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey_initWithLibOrgBouncycastlePqcJcajceSpecRainbowPrivateKeySpec_(LibOrgBouncycastlePqcJcajceSpecRainbowPrivateKeySpec *keySpec) {
  J2OBJC_NEW_IMPL(LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey, initWithLibOrgBouncycastlePqcJcajceSpecRainbowPrivateKeySpec_, keySpec)
}

LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey *create_LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey_initWithLibOrgBouncycastlePqcJcajceSpecRainbowPrivateKeySpec_(LibOrgBouncycastlePqcJcajceSpecRainbowPrivateKeySpec *keySpec) {
  J2OBJC_CREATE_IMPL(LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey, initWithLibOrgBouncycastlePqcJcajceSpecRainbowPrivateKeySpec_, keySpec)
}

void LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey_initWithLibOrgBouncycastlePqcCryptoRainbowRainbowPrivateKeyParameters_(LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey *self, LibOrgBouncycastlePqcCryptoRainbowRainbowPrivateKeyParameters *params) {
  LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey_initWithShortArray2_withShortArray_withShortArray2_withShortArray_withIntArray_withLibOrgBouncycastlePqcCryptoRainbowLayerArray_(self, [((LibOrgBouncycastlePqcCryptoRainbowRainbowPrivateKeyParameters *) nil_chk(params)) getInvA1], [params getB1], [params getInvA2], [params getB2], [params getVi], [params getLayers]);
}

LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey *new_LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey_initWithLibOrgBouncycastlePqcCryptoRainbowRainbowPrivateKeyParameters_(LibOrgBouncycastlePqcCryptoRainbowRainbowPrivateKeyParameters *params) {
  J2OBJC_NEW_IMPL(LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey, initWithLibOrgBouncycastlePqcCryptoRainbowRainbowPrivateKeyParameters_, params)
}

LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey *create_LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey_initWithLibOrgBouncycastlePqcCryptoRainbowRainbowPrivateKeyParameters_(LibOrgBouncycastlePqcCryptoRainbowRainbowPrivateKeyParameters *params) {
  J2OBJC_CREATE_IMPL(LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey, initWithLibOrgBouncycastlePqcCryptoRainbowRainbowPrivateKeyParameters_, params)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(LibOrgBouncycastlePqcJcajceProviderRainbowBCRainbowPrivateKey)
