//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/asn1/cmc/CMCStatusInfoV2.java
//

#include "ASN1Encodable.h"
#include "ASN1EncodableVector.h"
#include "ASN1Object.h"
#include "ASN1Primitive.h"
#include "ASN1Sequence.h"
#include "Asn1CmcUtils.h"
#include "CMCStatus.h"
#include "CMCStatusInfoV2.h"
#include "DERSequence.h"
#include "DERUTF8String.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "OtherStatusInfo.h"
#include "java/lang/IllegalArgumentException.h"

@interface LibOrgBouncycastleAsn1CmcCMCStatusInfoV2 () {
 @public
  LibOrgBouncycastleAsn1CmcCMCStatus *cMCStatus_;
  LibOrgBouncycastleAsn1ASN1Sequence *bodyList_;
  LibOrgBouncycastleAsn1DERUTF8String *statusString_;
  LibOrgBouncycastleAsn1CmcOtherStatusInfo *otherStatusInfo_;
}

- (instancetype)initWithLibOrgBouncycastleAsn1ASN1Sequence:(LibOrgBouncycastleAsn1ASN1Sequence *)seq;

@end

J2OBJC_FIELD_SETTER(LibOrgBouncycastleAsn1CmcCMCStatusInfoV2, cMCStatus_, LibOrgBouncycastleAsn1CmcCMCStatus *)
J2OBJC_FIELD_SETTER(LibOrgBouncycastleAsn1CmcCMCStatusInfoV2, bodyList_, LibOrgBouncycastleAsn1ASN1Sequence *)
J2OBJC_FIELD_SETTER(LibOrgBouncycastleAsn1CmcCMCStatusInfoV2, statusString_, LibOrgBouncycastleAsn1DERUTF8String *)
J2OBJC_FIELD_SETTER(LibOrgBouncycastleAsn1CmcCMCStatusInfoV2, otherStatusInfo_, LibOrgBouncycastleAsn1CmcOtherStatusInfo *)

__attribute__((unused)) static void LibOrgBouncycastleAsn1CmcCMCStatusInfoV2_initWithLibOrgBouncycastleAsn1ASN1Sequence_(LibOrgBouncycastleAsn1CmcCMCStatusInfoV2 *self, LibOrgBouncycastleAsn1ASN1Sequence *seq);

__attribute__((unused)) static LibOrgBouncycastleAsn1CmcCMCStatusInfoV2 *new_LibOrgBouncycastleAsn1CmcCMCStatusInfoV2_initWithLibOrgBouncycastleAsn1ASN1Sequence_(LibOrgBouncycastleAsn1ASN1Sequence *seq) NS_RETURNS_RETAINED;

__attribute__((unused)) static LibOrgBouncycastleAsn1CmcCMCStatusInfoV2 *create_LibOrgBouncycastleAsn1CmcCMCStatusInfoV2_initWithLibOrgBouncycastleAsn1ASN1Sequence_(LibOrgBouncycastleAsn1ASN1Sequence *seq);

@implementation LibOrgBouncycastleAsn1CmcCMCStatusInfoV2

- (instancetype)initWithLibOrgBouncycastleAsn1CmcCMCStatus:(LibOrgBouncycastleAsn1CmcCMCStatus *)cMCStatus
                    withLibOrgBouncycastleAsn1ASN1Sequence:(LibOrgBouncycastleAsn1ASN1Sequence *)bodyList
                   withLibOrgBouncycastleAsn1DERUTF8String:(LibOrgBouncycastleAsn1DERUTF8String *)statusString
              withLibOrgBouncycastleAsn1CmcOtherStatusInfo:(LibOrgBouncycastleAsn1CmcOtherStatusInfo *)otherStatusInfo {
  LibOrgBouncycastleAsn1CmcCMCStatusInfoV2_initWithLibOrgBouncycastleAsn1CmcCMCStatus_withLibOrgBouncycastleAsn1ASN1Sequence_withLibOrgBouncycastleAsn1DERUTF8String_withLibOrgBouncycastleAsn1CmcOtherStatusInfo_(self, cMCStatus, bodyList, statusString, otherStatusInfo);
  return self;
}

- (instancetype)initWithLibOrgBouncycastleAsn1ASN1Sequence:(LibOrgBouncycastleAsn1ASN1Sequence *)seq {
  LibOrgBouncycastleAsn1CmcCMCStatusInfoV2_initWithLibOrgBouncycastleAsn1ASN1Sequence_(self, seq);
  return self;
}

- (LibOrgBouncycastleAsn1CmcCMCStatus *)getcMCStatus {
  return cMCStatus_;
}

- (IOSObjectArray *)getBodyList {
  return LibOrgBouncycastleAsn1CmcAsn1CmcUtils_toBodyPartIDArrayWithLibOrgBouncycastleAsn1ASN1Sequence_(bodyList_);
}

- (LibOrgBouncycastleAsn1DERUTF8String *)getStatusString {
  return statusString_;
}

- (LibOrgBouncycastleAsn1CmcOtherStatusInfo *)getOtherStatusInfo {
  return otherStatusInfo_;
}

- (jboolean)hasOtherInfo {
  return otherStatusInfo_ != nil;
}

+ (LibOrgBouncycastleAsn1CmcCMCStatusInfoV2 *)getInstanceWithId:(id)o {
  return LibOrgBouncycastleAsn1CmcCMCStatusInfoV2_getInstanceWithId_(o);
}

- (LibOrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive {
  LibOrgBouncycastleAsn1ASN1EncodableVector *v = new_LibOrgBouncycastleAsn1ASN1EncodableVector_init();
  [v addWithLibOrgBouncycastleAsn1ASN1Encodable:cMCStatus_];
  [v addWithLibOrgBouncycastleAsn1ASN1Encodable:bodyList_];
  if (statusString_ != nil) {
    [v addWithLibOrgBouncycastleAsn1ASN1Encodable:statusString_];
  }
  if (otherStatusInfo_ != nil) {
    [v addWithLibOrgBouncycastleAsn1ASN1Encodable:otherStatusInfo_];
  }
  return new_LibOrgBouncycastleAsn1DERSequence_initWithLibOrgBouncycastleAsn1ASN1EncodableVector_(v);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x2, -1, 1, -1, -1, -1, -1 },
    { NULL, "LLibOrgBouncycastleAsn1CmcCMCStatus;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[LLibOrgBouncycastleAsn1CmcBodyPartID;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LLibOrgBouncycastleAsn1DERUTF8String;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LLibOrgBouncycastleAsn1CmcOtherStatusInfo;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LLibOrgBouncycastleAsn1CmcCMCStatusInfoV2;", 0x9, 2, 3, -1, -1, -1, -1 },
    { NULL, "LLibOrgBouncycastleAsn1ASN1Primitive;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithLibOrgBouncycastleAsn1CmcCMCStatus:withLibOrgBouncycastleAsn1ASN1Sequence:withLibOrgBouncycastleAsn1DERUTF8String:withLibOrgBouncycastleAsn1CmcOtherStatusInfo:);
  methods[1].selector = @selector(initWithLibOrgBouncycastleAsn1ASN1Sequence:);
  methods[2].selector = @selector(getcMCStatus);
  methods[3].selector = @selector(getBodyList);
  methods[4].selector = @selector(getStatusString);
  methods[5].selector = @selector(getOtherStatusInfo);
  methods[6].selector = @selector(hasOtherInfo);
  methods[7].selector = @selector(getInstanceWithId:);
  methods[8].selector = @selector(toASN1Primitive);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "cMCStatus_", "LLibOrgBouncycastleAsn1CmcCMCStatus;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "bodyList_", "LLibOrgBouncycastleAsn1ASN1Sequence;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "statusString_", "LLibOrgBouncycastleAsn1DERUTF8String;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "otherStatusInfo_", "LLibOrgBouncycastleAsn1CmcOtherStatusInfo;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LLibOrgBouncycastleAsn1CmcCMCStatus;LLibOrgBouncycastleAsn1ASN1Sequence;LLibOrgBouncycastleAsn1DERUTF8String;LLibOrgBouncycastleAsn1CmcOtherStatusInfo;", "LLibOrgBouncycastleAsn1ASN1Sequence;", "getInstance", "LNSObject;" };
  static const J2ObjcClassInfo _LibOrgBouncycastleAsn1CmcCMCStatusInfoV2 = { "CMCStatusInfoV2", "lib.org.bouncycastle.asn1.cmc", ptrTable, methods, fields, 7, 0x1, 9, 4, -1, -1, -1, -1, -1 };
  return &_LibOrgBouncycastleAsn1CmcCMCStatusInfoV2;
}

@end

void LibOrgBouncycastleAsn1CmcCMCStatusInfoV2_initWithLibOrgBouncycastleAsn1CmcCMCStatus_withLibOrgBouncycastleAsn1ASN1Sequence_withLibOrgBouncycastleAsn1DERUTF8String_withLibOrgBouncycastleAsn1CmcOtherStatusInfo_(LibOrgBouncycastleAsn1CmcCMCStatusInfoV2 *self, LibOrgBouncycastleAsn1CmcCMCStatus *cMCStatus, LibOrgBouncycastleAsn1ASN1Sequence *bodyList, LibOrgBouncycastleAsn1DERUTF8String *statusString, LibOrgBouncycastleAsn1CmcOtherStatusInfo *otherStatusInfo) {
  LibOrgBouncycastleAsn1ASN1Object_init(self);
  self->cMCStatus_ = cMCStatus;
  self->bodyList_ = bodyList;
  self->statusString_ = statusString;
  self->otherStatusInfo_ = otherStatusInfo;
}

LibOrgBouncycastleAsn1CmcCMCStatusInfoV2 *new_LibOrgBouncycastleAsn1CmcCMCStatusInfoV2_initWithLibOrgBouncycastleAsn1CmcCMCStatus_withLibOrgBouncycastleAsn1ASN1Sequence_withLibOrgBouncycastleAsn1DERUTF8String_withLibOrgBouncycastleAsn1CmcOtherStatusInfo_(LibOrgBouncycastleAsn1CmcCMCStatus *cMCStatus, LibOrgBouncycastleAsn1ASN1Sequence *bodyList, LibOrgBouncycastleAsn1DERUTF8String *statusString, LibOrgBouncycastleAsn1CmcOtherStatusInfo *otherStatusInfo) {
  J2OBJC_NEW_IMPL(LibOrgBouncycastleAsn1CmcCMCStatusInfoV2, initWithLibOrgBouncycastleAsn1CmcCMCStatus_withLibOrgBouncycastleAsn1ASN1Sequence_withLibOrgBouncycastleAsn1DERUTF8String_withLibOrgBouncycastleAsn1CmcOtherStatusInfo_, cMCStatus, bodyList, statusString, otherStatusInfo)
}

LibOrgBouncycastleAsn1CmcCMCStatusInfoV2 *create_LibOrgBouncycastleAsn1CmcCMCStatusInfoV2_initWithLibOrgBouncycastleAsn1CmcCMCStatus_withLibOrgBouncycastleAsn1ASN1Sequence_withLibOrgBouncycastleAsn1DERUTF8String_withLibOrgBouncycastleAsn1CmcOtherStatusInfo_(LibOrgBouncycastleAsn1CmcCMCStatus *cMCStatus, LibOrgBouncycastleAsn1ASN1Sequence *bodyList, LibOrgBouncycastleAsn1DERUTF8String *statusString, LibOrgBouncycastleAsn1CmcOtherStatusInfo *otherStatusInfo) {
  J2OBJC_CREATE_IMPL(LibOrgBouncycastleAsn1CmcCMCStatusInfoV2, initWithLibOrgBouncycastleAsn1CmcCMCStatus_withLibOrgBouncycastleAsn1ASN1Sequence_withLibOrgBouncycastleAsn1DERUTF8String_withLibOrgBouncycastleAsn1CmcOtherStatusInfo_, cMCStatus, bodyList, statusString, otherStatusInfo)
}

void LibOrgBouncycastleAsn1CmcCMCStatusInfoV2_initWithLibOrgBouncycastleAsn1ASN1Sequence_(LibOrgBouncycastleAsn1CmcCMCStatusInfoV2 *self, LibOrgBouncycastleAsn1ASN1Sequence *seq) {
  LibOrgBouncycastleAsn1ASN1Object_init(self);
  if ([((LibOrgBouncycastleAsn1ASN1Sequence *) nil_chk(seq)) size] < 2 || [seq size] > 4) {
    @throw new_JavaLangIllegalArgumentException_initWithNSString_(@"incorrect sequence size");
  }
  self->cMCStatus_ = LibOrgBouncycastleAsn1CmcCMCStatus_getInstanceWithId_([seq getObjectAtWithInt:0]);
  self->bodyList_ = LibOrgBouncycastleAsn1ASN1Sequence_getInstanceWithId_([seq getObjectAtWithInt:1]);
  if ([seq size] > 2) {
    if ([seq size] == 4) {
      self->statusString_ = LibOrgBouncycastleAsn1DERUTF8String_getInstanceWithId_([seq getObjectAtWithInt:2]);
      self->otherStatusInfo_ = LibOrgBouncycastleAsn1CmcOtherStatusInfo_getInstanceWithId_([seq getObjectAtWithInt:3]);
    }
    else if ([[seq getObjectAtWithInt:2] isKindOfClass:[LibOrgBouncycastleAsn1DERUTF8String class]]) {
      self->statusString_ = LibOrgBouncycastleAsn1DERUTF8String_getInstanceWithId_([seq getObjectAtWithInt:2]);
      self->otherStatusInfo_ = nil;
    }
    else {
      self->statusString_ = nil;
      self->otherStatusInfo_ = LibOrgBouncycastleAsn1CmcOtherStatusInfo_getInstanceWithId_([seq getObjectAtWithInt:2]);
    }
  }
  else {
    self->statusString_ = nil;
    self->otherStatusInfo_ = nil;
  }
}

LibOrgBouncycastleAsn1CmcCMCStatusInfoV2 *new_LibOrgBouncycastleAsn1CmcCMCStatusInfoV2_initWithLibOrgBouncycastleAsn1ASN1Sequence_(LibOrgBouncycastleAsn1ASN1Sequence *seq) {
  J2OBJC_NEW_IMPL(LibOrgBouncycastleAsn1CmcCMCStatusInfoV2, initWithLibOrgBouncycastleAsn1ASN1Sequence_, seq)
}

LibOrgBouncycastleAsn1CmcCMCStatusInfoV2 *create_LibOrgBouncycastleAsn1CmcCMCStatusInfoV2_initWithLibOrgBouncycastleAsn1ASN1Sequence_(LibOrgBouncycastleAsn1ASN1Sequence *seq) {
  J2OBJC_CREATE_IMPL(LibOrgBouncycastleAsn1CmcCMCStatusInfoV2, initWithLibOrgBouncycastleAsn1ASN1Sequence_, seq)
}

LibOrgBouncycastleAsn1CmcCMCStatusInfoV2 *LibOrgBouncycastleAsn1CmcCMCStatusInfoV2_getInstanceWithId_(id o) {
  LibOrgBouncycastleAsn1CmcCMCStatusInfoV2_initialize();
  if ([o isKindOfClass:[LibOrgBouncycastleAsn1CmcCMCStatusInfoV2 class]]) {
    return (LibOrgBouncycastleAsn1CmcCMCStatusInfoV2 *) o;
  }
  if (o != nil) {
    return new_LibOrgBouncycastleAsn1CmcCMCStatusInfoV2_initWithLibOrgBouncycastleAsn1ASN1Sequence_(LibOrgBouncycastleAsn1ASN1Sequence_getInstanceWithId_(o));
  }
  return nil;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(LibOrgBouncycastleAsn1CmcCMCStatusInfoV2)
