//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/crypto/prng/drbg/CryptoPrngDrbgUtils.java
//

#include "CryptoPrngDrbgUtils.h"
#include "Digest.h"
#include "IOSPrimitiveArray.h"
#include "Integers.h"
#include "J2ObjC_source.h"
#include "Mac.h"
#include "java/lang/Integer.h"
#include "java/lang/System.h"
#include "java/util/Hashtable.h"

J2OBJC_INITIALIZED_DEFN(LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils)

JavaUtilHashtable *LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_maxSecurityStrengths;

@implementation LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils

+ (JavaUtilHashtable *)maxSecurityStrengths {
  return LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_maxSecurityStrengths;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (jint)getMaxSecurityStrengthWithLibOrgBouncycastleCryptoDigest:(id<LibOrgBouncycastleCryptoDigest>)d {
  return LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_getMaxSecurityStrengthWithLibOrgBouncycastleCryptoDigest_(d);
}

+ (jint)getMaxSecurityStrengthWithLibOrgBouncycastleCryptoMac:(id<LibOrgBouncycastleCryptoMac>)m {
  return LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_getMaxSecurityStrengthWithLibOrgBouncycastleCryptoMac_(m);
}

+ (IOSByteArray *)hash_dfWithLibOrgBouncycastleCryptoDigest:(id<LibOrgBouncycastleCryptoDigest>)digest
                                              withByteArray:(IOSByteArray *)seedMaterial
                                                    withInt:(jint)seedLength {
  return LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_hash_dfWithLibOrgBouncycastleCryptoDigest_withByteArray_withInt_(digest, seedMaterial, seedLength);
}

+ (jboolean)isTooLargeWithByteArray:(IOSByteArray *)bytes
                            withInt:(jint)maxBytes {
  return LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_isTooLargeWithByteArray_withInt_(bytes, maxBytes);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x8, 0, 1, -1, -1, -1, -1 },
    { NULL, "I", 0x8, 0, 2, -1, -1, -1, -1 },
    { NULL, "[B", 0x8, 3, 4, -1, -1, -1, -1 },
    { NULL, "Z", 0x8, 5, 6, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getMaxSecurityStrengthWithLibOrgBouncycastleCryptoDigest:);
  methods[2].selector = @selector(getMaxSecurityStrengthWithLibOrgBouncycastleCryptoMac:);
  methods[3].selector = @selector(hash_dfWithLibOrgBouncycastleCryptoDigest:withByteArray:withInt:);
  methods[4].selector = @selector(isTooLargeWithByteArray:withInt:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "maxSecurityStrengths", "LJavaUtilHashtable;", .constantValue.asLong = 0, 0x18, -1, 7, -1, -1 },
  };
  static const void *ptrTable[] = { "getMaxSecurityStrength", "LLibOrgBouncycastleCryptoDigest;", "LLibOrgBouncycastleCryptoMac;", "hash_df", "LLibOrgBouncycastleCryptoDigest;[BI", "isTooLarge", "[BI", &LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_maxSecurityStrengths };
  static const J2ObjcClassInfo _LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils = { "CryptoPrngDrbgUtils", "lib.org.bouncycastle.crypto.prng.drbg", ptrTable, methods, fields, 7, 0x0, 5, 1, -1, -1, -1, -1, -1 };
  return &_LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils;
}

+ (void)initialize {
  if (self == [LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils class]) {
    LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_maxSecurityStrengths = new_JavaUtilHashtable_init();
    {
      (void) [LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_maxSecurityStrengths putWithId:@"SHA-1" withId:LibOrgBouncycastleUtilIntegers_valueOfWithInt_(128)];
      (void) [LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_maxSecurityStrengths putWithId:@"SHA-224" withId:LibOrgBouncycastleUtilIntegers_valueOfWithInt_(192)];
      (void) [LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_maxSecurityStrengths putWithId:@"SHA-256" withId:LibOrgBouncycastleUtilIntegers_valueOfWithInt_(256)];
      (void) [LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_maxSecurityStrengths putWithId:@"SHA-384" withId:LibOrgBouncycastleUtilIntegers_valueOfWithInt_(256)];
      (void) [LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_maxSecurityStrengths putWithId:@"SHA-512" withId:LibOrgBouncycastleUtilIntegers_valueOfWithInt_(256)];
      (void) [LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_maxSecurityStrengths putWithId:@"SHA-512/224" withId:LibOrgBouncycastleUtilIntegers_valueOfWithInt_(192)];
      (void) [LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_maxSecurityStrengths putWithId:@"SHA-512/256" withId:LibOrgBouncycastleUtilIntegers_valueOfWithInt_(256)];
    }
    J2OBJC_SET_INITIALIZED(LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils)
  }
}

@end

void LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_init(LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils *self) {
  NSObject_init(self);
}

LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils *new_LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_init() {
  J2OBJC_NEW_IMPL(LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils, init)
}

LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils *create_LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_init() {
  J2OBJC_CREATE_IMPL(LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils, init)
}

jint LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_getMaxSecurityStrengthWithLibOrgBouncycastleCryptoDigest_(id<LibOrgBouncycastleCryptoDigest> d) {
  LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_initialize();
  return [((JavaLangInteger *) nil_chk(((JavaLangInteger *) cast_chk([((JavaUtilHashtable *) nil_chk(LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_maxSecurityStrengths)) getWithId:[((id<LibOrgBouncycastleCryptoDigest>) nil_chk(d)) getAlgorithmName]], [JavaLangInteger class])))) intValue];
}

jint LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_getMaxSecurityStrengthWithLibOrgBouncycastleCryptoMac_(id<LibOrgBouncycastleCryptoMac> m) {
  LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_initialize();
  NSString *name = [((id<LibOrgBouncycastleCryptoMac>) nil_chk(m)) getAlgorithmName];
  return [((JavaLangInteger *) nil_chk(((JavaLangInteger *) cast_chk([((JavaUtilHashtable *) nil_chk(LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_maxSecurityStrengths)) getWithId:[((NSString *) nil_chk(name)) java_substring:0 endIndex:[name java_indexOfString:@"/"]]], [JavaLangInteger class])))) intValue];
}

IOSByteArray *LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_hash_dfWithLibOrgBouncycastleCryptoDigest_withByteArray_withInt_(id<LibOrgBouncycastleCryptoDigest> digest, IOSByteArray *seedMaterial, jint seedLength) {
  LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_initialize();
  IOSByteArray *temp = [IOSByteArray newArrayWithLength:(seedLength + 7) / 8];
  jint len = temp->size_ / [((id<LibOrgBouncycastleCryptoDigest>) nil_chk(digest)) getDigestSize];
  jint counter = 1;
  IOSByteArray *dig = [IOSByteArray newArrayWithLength:[digest getDigestSize]];
  for (jint i = 0; i <= len; i++) {
    [digest updateWithByte:(jbyte) counter];
    [digest updateWithByte:(jbyte) (JreRShift32(seedLength, 24))];
    [digest updateWithByte:(jbyte) (JreRShift32(seedLength, 16))];
    [digest updateWithByte:(jbyte) (JreRShift32(seedLength, 8))];
    [digest updateWithByte:(jbyte) seedLength];
    [digest updateWithByteArray:seedMaterial withInt:0 withInt:((IOSByteArray *) nil_chk(seedMaterial))->size_];
    [digest doFinalWithByteArray:dig withInt:0];
    jint bytesToCopy = ((temp->size_ - i * dig->size_) > dig->size_) ? dig->size_ : (temp->size_ - i * dig->size_);
    JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(dig, 0, temp, i * dig->size_, bytesToCopy);
    counter++;
  }
  if (seedLength % 8 != 0) {
    jint shift = 8 - (seedLength % 8);
    jint carry = 0;
    for (jint i = 0; i != temp->size_; i++) {
      jint b = IOSByteArray_Get(temp, i) & (jint) 0xff;
      *IOSByteArray_GetRef(temp, i) = (jbyte) ((JreURShift32(b, shift)) | (JreLShift32(carry, (8 - shift))));
      carry = b;
    }
  }
  return temp;
}

jboolean LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_isTooLargeWithByteArray_withInt_(IOSByteArray *bytes, jint maxBytes) {
  LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils_initialize();
  return bytes != nil && bytes->size_ > maxBytes;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(LibOrgBouncycastleCryptoPrngDrbgCryptoPrngDrbgUtils)
