//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/asn1/DLExternal.java
//

#ifndef DLExternal_H
#define DLExternal_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "ASN1External.h"
#include "J2ObjC_header.h"

@class LibOrgBouncycastleAsn1ASN1EncodableVector;
@class LibOrgBouncycastleAsn1ASN1Integer;
@class LibOrgBouncycastleAsn1ASN1ObjectIdentifier;
@class LibOrgBouncycastleAsn1ASN1OutputStream;
@class LibOrgBouncycastleAsn1ASN1Primitive;
@class LibOrgBouncycastleAsn1DERTaggedObject;

@interface LibOrgBouncycastleAsn1DLExternal : LibOrgBouncycastleAsn1ASN1External

#pragma mark Public

- (instancetype __nonnull)initWithLibOrgBouncycastleAsn1ASN1EncodableVector:(LibOrgBouncycastleAsn1ASN1EncodableVector *)vector;

- (instancetype __nonnull)initWithLibOrgBouncycastleAsn1ASN1ObjectIdentifier:(LibOrgBouncycastleAsn1ASN1ObjectIdentifier *)directReference
                                       withLibOrgBouncycastleAsn1ASN1Integer:(LibOrgBouncycastleAsn1ASN1Integer *)indirectReference
                                     withLibOrgBouncycastleAsn1ASN1Primitive:(LibOrgBouncycastleAsn1ASN1Primitive *)dataValueDescriptor
                                   withLibOrgBouncycastleAsn1DERTaggedObject:(LibOrgBouncycastleAsn1DERTaggedObject *)externalData;

- (instancetype __nonnull)initWithLibOrgBouncycastleAsn1ASN1ObjectIdentifier:(LibOrgBouncycastleAsn1ASN1ObjectIdentifier *)directReference
                                       withLibOrgBouncycastleAsn1ASN1Integer:(LibOrgBouncycastleAsn1ASN1Integer *)indirectReference
                                     withLibOrgBouncycastleAsn1ASN1Primitive:(LibOrgBouncycastleAsn1ASN1Primitive *)dataValueDescriptor
                                                                     withInt:(jint)encoding
                                     withLibOrgBouncycastleAsn1ASN1Primitive:(LibOrgBouncycastleAsn1ASN1Primitive *)externalData;

#pragma mark Package-Private

- (void)encodeWithLibOrgBouncycastleAsn1ASN1OutputStream:(LibOrgBouncycastleAsn1ASN1OutputStream *)outArg;

- (jint)encodedLength;

@end

J2OBJC_EMPTY_STATIC_INIT(LibOrgBouncycastleAsn1DLExternal)

FOUNDATION_EXPORT void LibOrgBouncycastleAsn1DLExternal_initWithLibOrgBouncycastleAsn1ASN1EncodableVector_(LibOrgBouncycastleAsn1DLExternal *self, LibOrgBouncycastleAsn1ASN1EncodableVector *vector);

FOUNDATION_EXPORT LibOrgBouncycastleAsn1DLExternal *new_LibOrgBouncycastleAsn1DLExternal_initWithLibOrgBouncycastleAsn1ASN1EncodableVector_(LibOrgBouncycastleAsn1ASN1EncodableVector *vector) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT LibOrgBouncycastleAsn1DLExternal *create_LibOrgBouncycastleAsn1DLExternal_initWithLibOrgBouncycastleAsn1ASN1EncodableVector_(LibOrgBouncycastleAsn1ASN1EncodableVector *vector);

FOUNDATION_EXPORT void LibOrgBouncycastleAsn1DLExternal_initWithLibOrgBouncycastleAsn1ASN1ObjectIdentifier_withLibOrgBouncycastleAsn1ASN1Integer_withLibOrgBouncycastleAsn1ASN1Primitive_withLibOrgBouncycastleAsn1DERTaggedObject_(LibOrgBouncycastleAsn1DLExternal *self, LibOrgBouncycastleAsn1ASN1ObjectIdentifier *directReference, LibOrgBouncycastleAsn1ASN1Integer *indirectReference, LibOrgBouncycastleAsn1ASN1Primitive *dataValueDescriptor, LibOrgBouncycastleAsn1DERTaggedObject *externalData);

FOUNDATION_EXPORT LibOrgBouncycastleAsn1DLExternal *new_LibOrgBouncycastleAsn1DLExternal_initWithLibOrgBouncycastleAsn1ASN1ObjectIdentifier_withLibOrgBouncycastleAsn1ASN1Integer_withLibOrgBouncycastleAsn1ASN1Primitive_withLibOrgBouncycastleAsn1DERTaggedObject_(LibOrgBouncycastleAsn1ASN1ObjectIdentifier *directReference, LibOrgBouncycastleAsn1ASN1Integer *indirectReference, LibOrgBouncycastleAsn1ASN1Primitive *dataValueDescriptor, LibOrgBouncycastleAsn1DERTaggedObject *externalData) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT LibOrgBouncycastleAsn1DLExternal *create_LibOrgBouncycastleAsn1DLExternal_initWithLibOrgBouncycastleAsn1ASN1ObjectIdentifier_withLibOrgBouncycastleAsn1ASN1Integer_withLibOrgBouncycastleAsn1ASN1Primitive_withLibOrgBouncycastleAsn1DERTaggedObject_(LibOrgBouncycastleAsn1ASN1ObjectIdentifier *directReference, LibOrgBouncycastleAsn1ASN1Integer *indirectReference, LibOrgBouncycastleAsn1ASN1Primitive *dataValueDescriptor, LibOrgBouncycastleAsn1DERTaggedObject *externalData);

FOUNDATION_EXPORT void LibOrgBouncycastleAsn1DLExternal_initWithLibOrgBouncycastleAsn1ASN1ObjectIdentifier_withLibOrgBouncycastleAsn1ASN1Integer_withLibOrgBouncycastleAsn1ASN1Primitive_withInt_withLibOrgBouncycastleAsn1ASN1Primitive_(LibOrgBouncycastleAsn1DLExternal *self, LibOrgBouncycastleAsn1ASN1ObjectIdentifier *directReference, LibOrgBouncycastleAsn1ASN1Integer *indirectReference, LibOrgBouncycastleAsn1ASN1Primitive *dataValueDescriptor, jint encoding, LibOrgBouncycastleAsn1ASN1Primitive *externalData);

FOUNDATION_EXPORT LibOrgBouncycastleAsn1DLExternal *new_LibOrgBouncycastleAsn1DLExternal_initWithLibOrgBouncycastleAsn1ASN1ObjectIdentifier_withLibOrgBouncycastleAsn1ASN1Integer_withLibOrgBouncycastleAsn1ASN1Primitive_withInt_withLibOrgBouncycastleAsn1ASN1Primitive_(LibOrgBouncycastleAsn1ASN1ObjectIdentifier *directReference, LibOrgBouncycastleAsn1ASN1Integer *indirectReference, LibOrgBouncycastleAsn1ASN1Primitive *dataValueDescriptor, jint encoding, LibOrgBouncycastleAsn1ASN1Primitive *externalData) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT LibOrgBouncycastleAsn1DLExternal *create_LibOrgBouncycastleAsn1DLExternal_initWithLibOrgBouncycastleAsn1ASN1ObjectIdentifier_withLibOrgBouncycastleAsn1ASN1Integer_withLibOrgBouncycastleAsn1ASN1Primitive_withInt_withLibOrgBouncycastleAsn1ASN1Primitive_(LibOrgBouncycastleAsn1ASN1ObjectIdentifier *directReference, LibOrgBouncycastleAsn1ASN1Integer *indirectReference, LibOrgBouncycastleAsn1ASN1Primitive *dataValueDescriptor, jint encoding, LibOrgBouncycastleAsn1ASN1Primitive *externalData);

J2OBJC_TYPE_LITERAL_HEADER(LibOrgBouncycastleAsn1DLExternal)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // DLExternal_H
