//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/asn1/ua/DSTU4145ECBinary.java
//

#ifndef DSTU4145ECBinary_H
#define DSTU4145ECBinary_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "ASN1Object.h"
#include "J2ObjC_header.h"

@class IOSByteArray;
@class JavaMathBigInteger;
@class LibOrgBouncycastleAsn1ASN1Integer;
@class LibOrgBouncycastleAsn1ASN1OctetString;
@class LibOrgBouncycastleAsn1ASN1Primitive;
@class LibOrgBouncycastleAsn1UaDSTU4145BinaryField;
@class LibOrgBouncycastleCryptoParamsECDomainParameters;

@interface LibOrgBouncycastleAsn1UaDSTU4145ECBinary : LibOrgBouncycastleAsn1ASN1Object {
 @public
  JavaMathBigInteger *version__;
  LibOrgBouncycastleAsn1UaDSTU4145BinaryField *f_;
  LibOrgBouncycastleAsn1ASN1Integer *a_;
  LibOrgBouncycastleAsn1ASN1OctetString *b_;
  LibOrgBouncycastleAsn1ASN1Integer *n_;
  LibOrgBouncycastleAsn1ASN1OctetString *bp_;
}

#pragma mark Public

- (instancetype __nonnull)initWithLibOrgBouncycastleCryptoParamsECDomainParameters:(LibOrgBouncycastleCryptoParamsECDomainParameters *)params;

- (JavaMathBigInteger *)getA;

- (IOSByteArray *)getB;

- (LibOrgBouncycastleAsn1UaDSTU4145BinaryField *)getField;

- (IOSByteArray *)getG;

+ (LibOrgBouncycastleAsn1UaDSTU4145ECBinary *)getInstanceWithId:(id)obj;

- (JavaMathBigInteger *)getN;

- (LibOrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(LibOrgBouncycastleAsn1UaDSTU4145ECBinary)

J2OBJC_FIELD_SETTER(LibOrgBouncycastleAsn1UaDSTU4145ECBinary, version__, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(LibOrgBouncycastleAsn1UaDSTU4145ECBinary, f_, LibOrgBouncycastleAsn1UaDSTU4145BinaryField *)
J2OBJC_FIELD_SETTER(LibOrgBouncycastleAsn1UaDSTU4145ECBinary, a_, LibOrgBouncycastleAsn1ASN1Integer *)
J2OBJC_FIELD_SETTER(LibOrgBouncycastleAsn1UaDSTU4145ECBinary, b_, LibOrgBouncycastleAsn1ASN1OctetString *)
J2OBJC_FIELD_SETTER(LibOrgBouncycastleAsn1UaDSTU4145ECBinary, n_, LibOrgBouncycastleAsn1ASN1Integer *)
J2OBJC_FIELD_SETTER(LibOrgBouncycastleAsn1UaDSTU4145ECBinary, bp_, LibOrgBouncycastleAsn1ASN1OctetString *)

FOUNDATION_EXPORT void LibOrgBouncycastleAsn1UaDSTU4145ECBinary_initWithLibOrgBouncycastleCryptoParamsECDomainParameters_(LibOrgBouncycastleAsn1UaDSTU4145ECBinary *self, LibOrgBouncycastleCryptoParamsECDomainParameters *params);

FOUNDATION_EXPORT LibOrgBouncycastleAsn1UaDSTU4145ECBinary *new_LibOrgBouncycastleAsn1UaDSTU4145ECBinary_initWithLibOrgBouncycastleCryptoParamsECDomainParameters_(LibOrgBouncycastleCryptoParamsECDomainParameters *params) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT LibOrgBouncycastleAsn1UaDSTU4145ECBinary *create_LibOrgBouncycastleAsn1UaDSTU4145ECBinary_initWithLibOrgBouncycastleCryptoParamsECDomainParameters_(LibOrgBouncycastleCryptoParamsECDomainParameters *params);

FOUNDATION_EXPORT LibOrgBouncycastleAsn1UaDSTU4145ECBinary *LibOrgBouncycastleAsn1UaDSTU4145ECBinary_getInstanceWithId_(id obj);

J2OBJC_TYPE_LITERAL_HEADER(LibOrgBouncycastleAsn1UaDSTU4145ECBinary)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // DSTU4145ECBinary_H
