//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/bcpg/sig/Features.java
//

#ifndef Features_H
#define Features_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"
#include "SignatureSubpacket.h"

@class IOSByteArray;

@interface LibOrgBouncycastleBcpgSigFeatures : LibOrgBouncycastleBcpgSignatureSubpacket
@property (readonly, class) jbyte FEATURE_MODIFICATION_DETECTION NS_SWIFT_NAME(FEATURE_MODIFICATION_DETECTION);

+ (jbyte)FEATURE_MODIFICATION_DETECTION;

#pragma mark Public

- (instancetype __nonnull)initWithBoolean:(jboolean)critical
                              withBoolean:(jboolean)isLongLength
                            withByteArray:(IOSByteArray *)data;

- (instancetype __nonnull)initWithBoolean:(jboolean)critical
                                 withByte:(jbyte)feature;

- (jboolean)supportsFeatureWithByte:(jbyte)feature;

- (jboolean)supportsModificationDetection;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithInt:(jint)arg0
                          withBoolean:(jboolean)arg1
                          withBoolean:(jboolean)arg2
                        withByteArray:(IOSByteArray *)arg3 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(LibOrgBouncycastleBcpgSigFeatures)

inline jbyte LibOrgBouncycastleBcpgSigFeatures_get_FEATURE_MODIFICATION_DETECTION(void);
#define LibOrgBouncycastleBcpgSigFeatures_FEATURE_MODIFICATION_DETECTION 1
J2OBJC_STATIC_FIELD_CONSTANT(LibOrgBouncycastleBcpgSigFeatures, FEATURE_MODIFICATION_DETECTION, jbyte)

FOUNDATION_EXPORT void LibOrgBouncycastleBcpgSigFeatures_initWithBoolean_withBoolean_withByteArray_(LibOrgBouncycastleBcpgSigFeatures *self, jboolean critical, jboolean isLongLength, IOSByteArray *data);

FOUNDATION_EXPORT LibOrgBouncycastleBcpgSigFeatures *new_LibOrgBouncycastleBcpgSigFeatures_initWithBoolean_withBoolean_withByteArray_(jboolean critical, jboolean isLongLength, IOSByteArray *data) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT LibOrgBouncycastleBcpgSigFeatures *create_LibOrgBouncycastleBcpgSigFeatures_initWithBoolean_withBoolean_withByteArray_(jboolean critical, jboolean isLongLength, IOSByteArray *data);

FOUNDATION_EXPORT void LibOrgBouncycastleBcpgSigFeatures_initWithBoolean_withByte_(LibOrgBouncycastleBcpgSigFeatures *self, jboolean critical, jbyte feature);

FOUNDATION_EXPORT LibOrgBouncycastleBcpgSigFeatures *new_LibOrgBouncycastleBcpgSigFeatures_initWithBoolean_withByte_(jboolean critical, jbyte feature) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT LibOrgBouncycastleBcpgSigFeatures *create_LibOrgBouncycastleBcpgSigFeatures_initWithBoolean_withByte_(jboolean critical, jbyte feature);

J2OBJC_TYPE_LITERAL_HEADER(LibOrgBouncycastleBcpgSigFeatures)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // Features_H
