//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/jcajce/provider/asymmetric/gost/GOSTUtil.java
//

#include "Arrays.h"
#include "Fingerprint.h"
#include "GOST3410Parameters.h"
#include "GOSTUtil.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "Strings.h"
#include "java/lang/StringBuffer.h"
#include "java/math/BigInteger.h"

@interface LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil ()

+ (NSString *)generateKeyFingerprintWithJavaMathBigInteger:(JavaMathBigInteger *)y
      withLibOrgBouncycastleCryptoParamsGOST3410Parameters:(LibOrgBouncycastleCryptoParamsGOST3410Parameters *)dhParams;

@end

__attribute__((unused)) static NSString *LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil_generateKeyFingerprintWithJavaMathBigInteger_withLibOrgBouncycastleCryptoParamsGOST3410Parameters_(JavaMathBigInteger *y, LibOrgBouncycastleCryptoParamsGOST3410Parameters *dhParams);

@implementation LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (NSString *)privateKeyToStringWithNSString:(NSString *)algorithm
                      withJavaMathBigInteger:(JavaMathBigInteger *)x
withLibOrgBouncycastleCryptoParamsGOST3410Parameters:(LibOrgBouncycastleCryptoParamsGOST3410Parameters *)gostParams {
  return LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil_privateKeyToStringWithNSString_withJavaMathBigInteger_withLibOrgBouncycastleCryptoParamsGOST3410Parameters_(algorithm, x, gostParams);
}

+ (NSString *)publicKeyToStringWithNSString:(NSString *)algorithm
                     withJavaMathBigInteger:(JavaMathBigInteger *)y
withLibOrgBouncycastleCryptoParamsGOST3410Parameters:(LibOrgBouncycastleCryptoParamsGOST3410Parameters *)gostParams {
  return LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil_publicKeyToStringWithNSString_withJavaMathBigInteger_withLibOrgBouncycastleCryptoParamsGOST3410Parameters_(algorithm, y, gostParams);
}

+ (NSString *)generateKeyFingerprintWithJavaMathBigInteger:(JavaMathBigInteger *)y
      withLibOrgBouncycastleCryptoParamsGOST3410Parameters:(LibOrgBouncycastleCryptoParamsGOST3410Parameters *)dhParams {
  return LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil_generateKeyFingerprintWithJavaMathBigInteger_withLibOrgBouncycastleCryptoParamsGOST3410Parameters_(y, dhParams);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x8, 0, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x8, 2, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0xa, 3, 4, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(privateKeyToStringWithNSString:withJavaMathBigInteger:withLibOrgBouncycastleCryptoParamsGOST3410Parameters:);
  methods[2].selector = @selector(publicKeyToStringWithNSString:withJavaMathBigInteger:withLibOrgBouncycastleCryptoParamsGOST3410Parameters:);
  methods[3].selector = @selector(generateKeyFingerprintWithJavaMathBigInteger:withLibOrgBouncycastleCryptoParamsGOST3410Parameters:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "privateKeyToString", "LNSString;LJavaMathBigInteger;LLibOrgBouncycastleCryptoParamsGOST3410Parameters;", "publicKeyToString", "generateKeyFingerprint", "LJavaMathBigInteger;LLibOrgBouncycastleCryptoParamsGOST3410Parameters;" };
  static const J2ObjcClassInfo _LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil = { "GOSTUtil", "lib.org.bouncycastle.jcajce.provider.asymmetric.gost", ptrTable, methods, NULL, 7, 0x0, 4, 0, -1, -1, -1, -1, -1 };
  return &_LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil;
}

@end

void LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil_init(LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil *self) {
  NSObject_init(self);
}

LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil *new_LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil_init() {
  J2OBJC_NEW_IMPL(LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil, init)
}

LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil *create_LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil_init() {
  J2OBJC_CREATE_IMPL(LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil, init)
}

NSString *LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil_privateKeyToStringWithNSString_withJavaMathBigInteger_withLibOrgBouncycastleCryptoParamsGOST3410Parameters_(NSString *algorithm, JavaMathBigInteger *x, LibOrgBouncycastleCryptoParamsGOST3410Parameters *gostParams) {
  LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil_initialize();
  JavaLangStringBuffer *buf = new_JavaLangStringBuffer_init();
  NSString *nl = LibOrgBouncycastleUtilStrings_lineSeparator();
  JavaMathBigInteger *y = [((JavaMathBigInteger *) nil_chk([((LibOrgBouncycastleCryptoParamsGOST3410Parameters *) nil_chk(gostParams)) getA])) modPowWithJavaMathBigInteger:x withJavaMathBigInteger:[gostParams getP]];
  (void) [buf appendWithNSString:algorithm];
  (void) [((JavaLangStringBuffer *) nil_chk([((JavaLangStringBuffer *) nil_chk([((JavaLangStringBuffer *) nil_chk([buf appendWithNSString:@" Private Key ["])) appendWithNSString:LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil_generateKeyFingerprintWithJavaMathBigInteger_withLibOrgBouncycastleCryptoParamsGOST3410Parameters_(y, gostParams)])) appendWithNSString:@"]"])) appendWithNSString:nl];
  (void) [((JavaLangStringBuffer *) nil_chk([((JavaLangStringBuffer *) nil_chk([buf appendWithNSString:@"                  Y: "])) appendWithNSString:[((JavaMathBigInteger *) nil_chk(y)) toStringWithInt:16]])) appendWithNSString:nl];
  return [buf description];
}

NSString *LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil_publicKeyToStringWithNSString_withJavaMathBigInteger_withLibOrgBouncycastleCryptoParamsGOST3410Parameters_(NSString *algorithm, JavaMathBigInteger *y, LibOrgBouncycastleCryptoParamsGOST3410Parameters *gostParams) {
  LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil_initialize();
  JavaLangStringBuffer *buf = new_JavaLangStringBuffer_init();
  NSString *nl = LibOrgBouncycastleUtilStrings_lineSeparator();
  (void) [buf appendWithNSString:algorithm];
  (void) [((JavaLangStringBuffer *) nil_chk([((JavaLangStringBuffer *) nil_chk([((JavaLangStringBuffer *) nil_chk([buf appendWithNSString:@" Public Key ["])) appendWithNSString:LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil_generateKeyFingerprintWithJavaMathBigInteger_withLibOrgBouncycastleCryptoParamsGOST3410Parameters_(y, gostParams)])) appendWithNSString:@"]"])) appendWithNSString:nl];
  (void) [((JavaLangStringBuffer *) nil_chk([((JavaLangStringBuffer *) nil_chk([buf appendWithNSString:@"                 Y: "])) appendWithNSString:[((JavaMathBigInteger *) nil_chk(y)) toStringWithInt:16]])) appendWithNSString:nl];
  return [buf description];
}

NSString *LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil_generateKeyFingerprintWithJavaMathBigInteger_withLibOrgBouncycastleCryptoParamsGOST3410Parameters_(JavaMathBigInteger *y, LibOrgBouncycastleCryptoParamsGOST3410Parameters *dhParams) {
  LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil_initialize();
  return [new_LibOrgBouncycastleUtilFingerprint_initWithByteArray_(LibOrgBouncycastleUtilArrays_concatenateWithByteArray_withByteArray_withByteArray_([((JavaMathBigInteger *) nil_chk(y)) toByteArray], [((JavaMathBigInteger *) nil_chk([((LibOrgBouncycastleCryptoParamsGOST3410Parameters *) nil_chk(dhParams)) getP])) toByteArray], [((JavaMathBigInteger *) nil_chk([dhParams getA])) toByteArray])) description];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(LibOrgBouncycastleJcajceProviderAsymmetricGostGOSTUtil)
