//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/jce/provider/JDKPKCS12StoreParameter.java
//

#ifndef JDKPKCS12StoreParameter_H
#define JDKPKCS12StoreParameter_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"
#include "java/security/KeyStore.h"

@class IOSCharArray;
@class JavaIoOutputStream;

@interface LibOrgBouncycastleJceProviderJDKPKCS12StoreParameter : NSObject < JavaSecurityKeyStore_LoadStoreParameter >

#pragma mark Public

- (instancetype __nonnull)init;

- (JavaIoOutputStream *)getOutputStream;

- (id<JavaSecurityKeyStore_ProtectionParameter>)getProtectionParameter;

- (jboolean)isUseDEREncoding;

- (void)setOutputStreamWithJavaIoOutputStream:(JavaIoOutputStream *)outputStream;

- (void)setPasswordWithCharArray:(IOSCharArray *)password;

- (void)setProtectionParameterWithJavaSecurityKeyStore_ProtectionParameter:(id<JavaSecurityKeyStore_ProtectionParameter>)protectionParameter;

- (void)setUseDEREncodingWithBoolean:(jboolean)useDEREncoding;

@end

J2OBJC_EMPTY_STATIC_INIT(LibOrgBouncycastleJceProviderJDKPKCS12StoreParameter)

FOUNDATION_EXPORT void LibOrgBouncycastleJceProviderJDKPKCS12StoreParameter_init(LibOrgBouncycastleJceProviderJDKPKCS12StoreParameter *self);

FOUNDATION_EXPORT LibOrgBouncycastleJceProviderJDKPKCS12StoreParameter *new_LibOrgBouncycastleJceProviderJDKPKCS12StoreParameter_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT LibOrgBouncycastleJceProviderJDKPKCS12StoreParameter *create_LibOrgBouncycastleJceProviderJDKPKCS12StoreParameter_init(void);

J2OBJC_TYPE_LITERAL_HEADER(LibOrgBouncycastleJceProviderJDKPKCS12StoreParameter)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // JDKPKCS12StoreParameter_H
