//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/crypto/agreement/jpake/JPAKERound3Payload.java
//

#ifndef JPAKERound3Payload_H
#define JPAKERound3Payload_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@class JavaMathBigInteger;

@interface LibOrgBouncycastleCryptoAgreementJpakeJPAKERound3Payload : NSObject

#pragma mark Public

- (instancetype __nonnull)initWithNSString:(NSString *)participantId
                    withJavaMathBigInteger:(JavaMathBigInteger *)magTag;

- (JavaMathBigInteger *)getMacTag;

- (NSString *)getParticipantId;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(LibOrgBouncycastleCryptoAgreementJpakeJPAKERound3Payload)

FOUNDATION_EXPORT void LibOrgBouncycastleCryptoAgreementJpakeJPAKERound3Payload_initWithNSString_withJavaMathBigInteger_(LibOrgBouncycastleCryptoAgreementJpakeJPAKERound3Payload *self, NSString *participantId, JavaMathBigInteger *magTag);

FOUNDATION_EXPORT LibOrgBouncycastleCryptoAgreementJpakeJPAKERound3Payload *new_LibOrgBouncycastleCryptoAgreementJpakeJPAKERound3Payload_initWithNSString_withJavaMathBigInteger_(NSString *participantId, JavaMathBigInteger *magTag) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT LibOrgBouncycastleCryptoAgreementJpakeJPAKERound3Payload *create_LibOrgBouncycastleCryptoAgreementJpakeJPAKERound3Payload_initWithNSString_withJavaMathBigInteger_(NSString *participantId, JavaMathBigInteger *magTag);

J2OBJC_TYPE_LITERAL_HEADER(LibOrgBouncycastleCryptoAgreementJpakeJPAKERound3Payload)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // JPAKERound3Payload_H
