//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/crypto/digests/MD5Digest.java
//

#ifndef MD5Digest_H
#define MD5Digest_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "EncodableDigest.h"
#include "GeneralDigest.h"
#include "J2ObjC_header.h"

@class IOSByteArray;
@protocol LibOrgBouncycastleUtilMemoable;

@interface LibOrgBouncycastleCryptoDigestsMD5Digest : LibOrgBouncycastleCryptoDigestsGeneralDigest < LibOrgBouncycastleCryptoDigestsEncodableDigest >

#pragma mark Public

- (instancetype __nonnull)init;

- (instancetype __nonnull)initWithByteArray:(IOSByteArray *)encodedState;

- (instancetype __nonnull)initWithLibOrgBouncycastleCryptoDigestsMD5Digest:(LibOrgBouncycastleCryptoDigestsMD5Digest *)t;

- (id<LibOrgBouncycastleUtilMemoable>)copy__ OBJC_METHOD_FAMILY_NONE;

- (jint)doFinalWithByteArray:(IOSByteArray *)outArg
                     withInt:(jint)outOff;

- (NSString *)getAlgorithmName;

- (jint)getDigestSize;

- (IOSByteArray *)getEncodedState;

- (void)reset;

- (void)resetWithLibOrgBouncycastleUtilMemoable:(id<LibOrgBouncycastleUtilMemoable>)other;

#pragma mark Protected

- (void)processBlock;

- (void)processLengthWithLong:(jlong)bitLength;

- (void)processWordWithByteArray:(IOSByteArray *)inArg
                         withInt:(jint)inOff;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithLibOrgBouncycastleCryptoDigestsGeneralDigest:(LibOrgBouncycastleCryptoDigestsGeneralDigest *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(LibOrgBouncycastleCryptoDigestsMD5Digest)

FOUNDATION_EXPORT void LibOrgBouncycastleCryptoDigestsMD5Digest_init(LibOrgBouncycastleCryptoDigestsMD5Digest *self);

FOUNDATION_EXPORT LibOrgBouncycastleCryptoDigestsMD5Digest *new_LibOrgBouncycastleCryptoDigestsMD5Digest_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT LibOrgBouncycastleCryptoDigestsMD5Digest *create_LibOrgBouncycastleCryptoDigestsMD5Digest_init(void);

FOUNDATION_EXPORT void LibOrgBouncycastleCryptoDigestsMD5Digest_initWithByteArray_(LibOrgBouncycastleCryptoDigestsMD5Digest *self, IOSByteArray *encodedState);

FOUNDATION_EXPORT LibOrgBouncycastleCryptoDigestsMD5Digest *new_LibOrgBouncycastleCryptoDigestsMD5Digest_initWithByteArray_(IOSByteArray *encodedState) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT LibOrgBouncycastleCryptoDigestsMD5Digest *create_LibOrgBouncycastleCryptoDigestsMD5Digest_initWithByteArray_(IOSByteArray *encodedState);

FOUNDATION_EXPORT void LibOrgBouncycastleCryptoDigestsMD5Digest_initWithLibOrgBouncycastleCryptoDigestsMD5Digest_(LibOrgBouncycastleCryptoDigestsMD5Digest *self, LibOrgBouncycastleCryptoDigestsMD5Digest *t);

FOUNDATION_EXPORT LibOrgBouncycastleCryptoDigestsMD5Digest *new_LibOrgBouncycastleCryptoDigestsMD5Digest_initWithLibOrgBouncycastleCryptoDigestsMD5Digest_(LibOrgBouncycastleCryptoDigestsMD5Digest *t) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT LibOrgBouncycastleCryptoDigestsMD5Digest *create_LibOrgBouncycastleCryptoDigestsMD5Digest_initWithLibOrgBouncycastleCryptoDigestsMD5Digest_(LibOrgBouncycastleCryptoDigestsMD5Digest *t);

J2OBJC_TYPE_LITERAL_HEADER(LibOrgBouncycastleCryptoDigestsMD5Digest)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // MD5Digest_H
