//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/asn1/cmc/PKIData.java
//

#include "ASN1Encodable.h"
#include "ASN1Object.h"
#include "ASN1Primitive.h"
#include "ASN1Sequence.h"
#include "DERSequence.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "OtherMsg.h"
#include "PKIData.h"
#include "TaggedAttribute.h"
#include "TaggedContentInfo.h"
#include "TaggedRequest.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/System.h"

@interface LibOrgBouncycastleAsn1CmcPKIData () {
 @public
  IOSObjectArray *controlSequence_;
  IOSObjectArray *reqSequence_;
  IOSObjectArray *cmsSequence_;
  IOSObjectArray *otherMsgSequence_;
}

- (instancetype)initWithLibOrgBouncycastleAsn1ASN1Sequence:(LibOrgBouncycastleAsn1ASN1Sequence *)seq;

- (IOSObjectArray *)copy__WithLibOrgBouncycastleAsn1CmcTaggedAttributeArray:(IOSObjectArray *)taggedAtts OBJC_METHOD_FAMILY_NONE;

- (IOSObjectArray *)copy__WithLibOrgBouncycastleAsn1CmcTaggedRequestArray:(IOSObjectArray *)taggedReqs OBJC_METHOD_FAMILY_NONE;

- (IOSObjectArray *)copy__WithLibOrgBouncycastleAsn1CmcTaggedContentInfoArray:(IOSObjectArray *)taggedConts OBJC_METHOD_FAMILY_NONE;

- (IOSObjectArray *)copy__WithLibOrgBouncycastleAsn1CmcOtherMsgArray:(IOSObjectArray *)otherMsgs OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_FIELD_SETTER(LibOrgBouncycastleAsn1CmcPKIData, controlSequence_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(LibOrgBouncycastleAsn1CmcPKIData, reqSequence_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(LibOrgBouncycastleAsn1CmcPKIData, cmsSequence_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(LibOrgBouncycastleAsn1CmcPKIData, otherMsgSequence_, IOSObjectArray *)

__attribute__((unused)) static void LibOrgBouncycastleAsn1CmcPKIData_initWithLibOrgBouncycastleAsn1ASN1Sequence_(LibOrgBouncycastleAsn1CmcPKIData *self, LibOrgBouncycastleAsn1ASN1Sequence *seq);

__attribute__((unused)) static LibOrgBouncycastleAsn1CmcPKIData *new_LibOrgBouncycastleAsn1CmcPKIData_initWithLibOrgBouncycastleAsn1ASN1Sequence_(LibOrgBouncycastleAsn1ASN1Sequence *seq) NS_RETURNS_RETAINED;

__attribute__((unused)) static LibOrgBouncycastleAsn1CmcPKIData *create_LibOrgBouncycastleAsn1CmcPKIData_initWithLibOrgBouncycastleAsn1ASN1Sequence_(LibOrgBouncycastleAsn1ASN1Sequence *seq);

__attribute__((unused)) static IOSObjectArray *LibOrgBouncycastleAsn1CmcPKIData_copy__WithLibOrgBouncycastleAsn1CmcTaggedAttributeArray_(LibOrgBouncycastleAsn1CmcPKIData *self, IOSObjectArray *taggedAtts);

__attribute__((unused)) static IOSObjectArray *LibOrgBouncycastleAsn1CmcPKIData_copy__WithLibOrgBouncycastleAsn1CmcTaggedRequestArray_(LibOrgBouncycastleAsn1CmcPKIData *self, IOSObjectArray *taggedReqs);

__attribute__((unused)) static IOSObjectArray *LibOrgBouncycastleAsn1CmcPKIData_copy__WithLibOrgBouncycastleAsn1CmcTaggedContentInfoArray_(LibOrgBouncycastleAsn1CmcPKIData *self, IOSObjectArray *taggedConts);

__attribute__((unused)) static IOSObjectArray *LibOrgBouncycastleAsn1CmcPKIData_copy__WithLibOrgBouncycastleAsn1CmcOtherMsgArray_(LibOrgBouncycastleAsn1CmcPKIData *self, IOSObjectArray *otherMsgs);

@implementation LibOrgBouncycastleAsn1CmcPKIData

- (instancetype)initWithLibOrgBouncycastleAsn1CmcTaggedAttributeArray:(IOSObjectArray *)controlSequence
                      withLibOrgBouncycastleAsn1CmcTaggedRequestArray:(IOSObjectArray *)reqSequence
                  withLibOrgBouncycastleAsn1CmcTaggedContentInfoArray:(IOSObjectArray *)cmsSequence
                           withLibOrgBouncycastleAsn1CmcOtherMsgArray:(IOSObjectArray *)otherMsgSequence {
  LibOrgBouncycastleAsn1CmcPKIData_initWithLibOrgBouncycastleAsn1CmcTaggedAttributeArray_withLibOrgBouncycastleAsn1CmcTaggedRequestArray_withLibOrgBouncycastleAsn1CmcTaggedContentInfoArray_withLibOrgBouncycastleAsn1CmcOtherMsgArray_(self, controlSequence, reqSequence, cmsSequence, otherMsgSequence);
  return self;
}

- (instancetype)initWithLibOrgBouncycastleAsn1ASN1Sequence:(LibOrgBouncycastleAsn1ASN1Sequence *)seq {
  LibOrgBouncycastleAsn1CmcPKIData_initWithLibOrgBouncycastleAsn1ASN1Sequence_(self, seq);
  return self;
}

+ (LibOrgBouncycastleAsn1CmcPKIData *)getInstanceWithId:(id)src {
  return LibOrgBouncycastleAsn1CmcPKIData_getInstanceWithId_(src);
}

- (LibOrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive {
  return new_LibOrgBouncycastleAsn1DERSequence_initWithLibOrgBouncycastleAsn1ASN1EncodableArray_([IOSObjectArray newArrayWithObjects:(id[]){ create_LibOrgBouncycastleAsn1DERSequence_initWithLibOrgBouncycastleAsn1ASN1EncodableArray_(controlSequence_), create_LibOrgBouncycastleAsn1DERSequence_initWithLibOrgBouncycastleAsn1ASN1EncodableArray_(reqSequence_), create_LibOrgBouncycastleAsn1DERSequence_initWithLibOrgBouncycastleAsn1ASN1EncodableArray_(cmsSequence_), create_LibOrgBouncycastleAsn1DERSequence_initWithLibOrgBouncycastleAsn1ASN1EncodableArray_(otherMsgSequence_) } count:4 type:LibOrgBouncycastleAsn1ASN1Encodable_class_()]);
}

- (IOSObjectArray *)getControlSequence {
  return LibOrgBouncycastleAsn1CmcPKIData_copy__WithLibOrgBouncycastleAsn1CmcTaggedAttributeArray_(self, controlSequence_);
}

- (IOSObjectArray *)copy__WithLibOrgBouncycastleAsn1CmcTaggedAttributeArray:(IOSObjectArray *)taggedAtts {
  return LibOrgBouncycastleAsn1CmcPKIData_copy__WithLibOrgBouncycastleAsn1CmcTaggedAttributeArray_(self, taggedAtts);
}

- (IOSObjectArray *)getReqSequence {
  return LibOrgBouncycastleAsn1CmcPKIData_copy__WithLibOrgBouncycastleAsn1CmcTaggedRequestArray_(self, reqSequence_);
}

- (IOSObjectArray *)copy__WithLibOrgBouncycastleAsn1CmcTaggedRequestArray:(IOSObjectArray *)taggedReqs {
  return LibOrgBouncycastleAsn1CmcPKIData_copy__WithLibOrgBouncycastleAsn1CmcTaggedRequestArray_(self, taggedReqs);
}

- (IOSObjectArray *)getCmsSequence {
  return LibOrgBouncycastleAsn1CmcPKIData_copy__WithLibOrgBouncycastleAsn1CmcTaggedContentInfoArray_(self, cmsSequence_);
}

- (IOSObjectArray *)copy__WithLibOrgBouncycastleAsn1CmcTaggedContentInfoArray:(IOSObjectArray *)taggedConts {
  return LibOrgBouncycastleAsn1CmcPKIData_copy__WithLibOrgBouncycastleAsn1CmcTaggedContentInfoArray_(self, taggedConts);
}

- (IOSObjectArray *)getOtherMsgSequence {
  return LibOrgBouncycastleAsn1CmcPKIData_copy__WithLibOrgBouncycastleAsn1CmcOtherMsgArray_(self, otherMsgSequence_);
}

- (IOSObjectArray *)copy__WithLibOrgBouncycastleAsn1CmcOtherMsgArray:(IOSObjectArray *)otherMsgs {
  return LibOrgBouncycastleAsn1CmcPKIData_copy__WithLibOrgBouncycastleAsn1CmcOtherMsgArray_(self, otherMsgs);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x2, -1, 1, -1, -1, -1, -1 },
    { NULL, "LLibOrgBouncycastleAsn1CmcPKIData;", 0x9, 2, 3, -1, -1, -1, -1 },
    { NULL, "LLibOrgBouncycastleAsn1ASN1Primitive;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[LLibOrgBouncycastleAsn1CmcTaggedAttribute;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[LLibOrgBouncycastleAsn1CmcTaggedAttribute;", 0x2, 4, 5, -1, -1, -1, -1 },
    { NULL, "[LLibOrgBouncycastleAsn1CmcTaggedRequest;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[LLibOrgBouncycastleAsn1CmcTaggedRequest;", 0x2, 4, 6, -1, -1, -1, -1 },
    { NULL, "[LLibOrgBouncycastleAsn1CmcTaggedContentInfo;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[LLibOrgBouncycastleAsn1CmcTaggedContentInfo;", 0x2, 4, 7, -1, -1, -1, -1 },
    { NULL, "[LLibOrgBouncycastleAsn1CmcOtherMsg;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[LLibOrgBouncycastleAsn1CmcOtherMsg;", 0x2, 4, 8, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithLibOrgBouncycastleAsn1CmcTaggedAttributeArray:withLibOrgBouncycastleAsn1CmcTaggedRequestArray:withLibOrgBouncycastleAsn1CmcTaggedContentInfoArray:withLibOrgBouncycastleAsn1CmcOtherMsgArray:);
  methods[1].selector = @selector(initWithLibOrgBouncycastleAsn1ASN1Sequence:);
  methods[2].selector = @selector(getInstanceWithId:);
  methods[3].selector = @selector(toASN1Primitive);
  methods[4].selector = @selector(getControlSequence);
  methods[5].selector = @selector(copy__WithLibOrgBouncycastleAsn1CmcTaggedAttributeArray:);
  methods[6].selector = @selector(getReqSequence);
  methods[7].selector = @selector(copy__WithLibOrgBouncycastleAsn1CmcTaggedRequestArray:);
  methods[8].selector = @selector(getCmsSequence);
  methods[9].selector = @selector(copy__WithLibOrgBouncycastleAsn1CmcTaggedContentInfoArray:);
  methods[10].selector = @selector(getOtherMsgSequence);
  methods[11].selector = @selector(copy__WithLibOrgBouncycastleAsn1CmcOtherMsgArray:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "controlSequence_", "[LLibOrgBouncycastleAsn1CmcTaggedAttribute;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "reqSequence_", "[LLibOrgBouncycastleAsn1CmcTaggedRequest;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "cmsSequence_", "[LLibOrgBouncycastleAsn1CmcTaggedContentInfo;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "otherMsgSequence_", "[LLibOrgBouncycastleAsn1CmcOtherMsg;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "[LLibOrgBouncycastleAsn1CmcTaggedAttribute;[LLibOrgBouncycastleAsn1CmcTaggedRequest;[LLibOrgBouncycastleAsn1CmcTaggedContentInfo;[LLibOrgBouncycastleAsn1CmcOtherMsg;", "LLibOrgBouncycastleAsn1ASN1Sequence;", "getInstance", "LNSObject;", "copy", "[LLibOrgBouncycastleAsn1CmcTaggedAttribute;", "[LLibOrgBouncycastleAsn1CmcTaggedRequest;", "[LLibOrgBouncycastleAsn1CmcTaggedContentInfo;", "[LLibOrgBouncycastleAsn1CmcOtherMsg;" };
  static const J2ObjcClassInfo _LibOrgBouncycastleAsn1CmcPKIData = { "PKIData", "lib.org.bouncycastle.asn1.cmc", ptrTable, methods, fields, 7, 0x1, 12, 4, -1, -1, -1, -1, -1 };
  return &_LibOrgBouncycastleAsn1CmcPKIData;
}

@end

void LibOrgBouncycastleAsn1CmcPKIData_initWithLibOrgBouncycastleAsn1CmcTaggedAttributeArray_withLibOrgBouncycastleAsn1CmcTaggedRequestArray_withLibOrgBouncycastleAsn1CmcTaggedContentInfoArray_withLibOrgBouncycastleAsn1CmcOtherMsgArray_(LibOrgBouncycastleAsn1CmcPKIData *self, IOSObjectArray *controlSequence, IOSObjectArray *reqSequence, IOSObjectArray *cmsSequence, IOSObjectArray *otherMsgSequence) {
  LibOrgBouncycastleAsn1ASN1Object_init(self);
  self->controlSequence_ = LibOrgBouncycastleAsn1CmcPKIData_copy__WithLibOrgBouncycastleAsn1CmcTaggedAttributeArray_(self, controlSequence);
  self->reqSequence_ = LibOrgBouncycastleAsn1CmcPKIData_copy__WithLibOrgBouncycastleAsn1CmcTaggedRequestArray_(self, reqSequence);
  self->cmsSequence_ = LibOrgBouncycastleAsn1CmcPKIData_copy__WithLibOrgBouncycastleAsn1CmcTaggedContentInfoArray_(self, cmsSequence);
  self->otherMsgSequence_ = LibOrgBouncycastleAsn1CmcPKIData_copy__WithLibOrgBouncycastleAsn1CmcOtherMsgArray_(self, otherMsgSequence);
}

LibOrgBouncycastleAsn1CmcPKIData *new_LibOrgBouncycastleAsn1CmcPKIData_initWithLibOrgBouncycastleAsn1CmcTaggedAttributeArray_withLibOrgBouncycastleAsn1CmcTaggedRequestArray_withLibOrgBouncycastleAsn1CmcTaggedContentInfoArray_withLibOrgBouncycastleAsn1CmcOtherMsgArray_(IOSObjectArray *controlSequence, IOSObjectArray *reqSequence, IOSObjectArray *cmsSequence, IOSObjectArray *otherMsgSequence) {
  J2OBJC_NEW_IMPL(LibOrgBouncycastleAsn1CmcPKIData, initWithLibOrgBouncycastleAsn1CmcTaggedAttributeArray_withLibOrgBouncycastleAsn1CmcTaggedRequestArray_withLibOrgBouncycastleAsn1CmcTaggedContentInfoArray_withLibOrgBouncycastleAsn1CmcOtherMsgArray_, controlSequence, reqSequence, cmsSequence, otherMsgSequence)
}

LibOrgBouncycastleAsn1CmcPKIData *create_LibOrgBouncycastleAsn1CmcPKIData_initWithLibOrgBouncycastleAsn1CmcTaggedAttributeArray_withLibOrgBouncycastleAsn1CmcTaggedRequestArray_withLibOrgBouncycastleAsn1CmcTaggedContentInfoArray_withLibOrgBouncycastleAsn1CmcOtherMsgArray_(IOSObjectArray *controlSequence, IOSObjectArray *reqSequence, IOSObjectArray *cmsSequence, IOSObjectArray *otherMsgSequence) {
  J2OBJC_CREATE_IMPL(LibOrgBouncycastleAsn1CmcPKIData, initWithLibOrgBouncycastleAsn1CmcTaggedAttributeArray_withLibOrgBouncycastleAsn1CmcTaggedRequestArray_withLibOrgBouncycastleAsn1CmcTaggedContentInfoArray_withLibOrgBouncycastleAsn1CmcOtherMsgArray_, controlSequence, reqSequence, cmsSequence, otherMsgSequence)
}

void LibOrgBouncycastleAsn1CmcPKIData_initWithLibOrgBouncycastleAsn1ASN1Sequence_(LibOrgBouncycastleAsn1CmcPKIData *self, LibOrgBouncycastleAsn1ASN1Sequence *seq) {
  LibOrgBouncycastleAsn1ASN1Object_init(self);
  if ([((LibOrgBouncycastleAsn1ASN1Sequence *) nil_chk(seq)) size] != 4) {
    @throw new_JavaLangIllegalArgumentException_initWithNSString_(@"Sequence not 4 elements.");
  }
  LibOrgBouncycastleAsn1ASN1Sequence *s = ((LibOrgBouncycastleAsn1ASN1Sequence *) cast_chk([seq getObjectAtWithInt:0], [LibOrgBouncycastleAsn1ASN1Sequence class]));
  self->controlSequence_ = [IOSObjectArray newArrayWithLength:[((LibOrgBouncycastleAsn1ASN1Sequence *) nil_chk(s)) size] type:LibOrgBouncycastleAsn1CmcTaggedAttribute_class_()];
  for (jint t = 0; t < self->controlSequence_->size_; t++) {
    (void) IOSObjectArray_Set(self->controlSequence_, t, LibOrgBouncycastleAsn1CmcTaggedAttribute_getInstanceWithId_([s getObjectAtWithInt:t]));
  }
  s = ((LibOrgBouncycastleAsn1ASN1Sequence *) cast_chk([seq getObjectAtWithInt:1], [LibOrgBouncycastleAsn1ASN1Sequence class]));
  self->reqSequence_ = [IOSObjectArray newArrayWithLength:[((LibOrgBouncycastleAsn1ASN1Sequence *) nil_chk(s)) size] type:LibOrgBouncycastleAsn1CmcTaggedRequest_class_()];
  for (jint t = 0; t < self->reqSequence_->size_; t++) {
    (void) IOSObjectArray_Set(self->reqSequence_, t, LibOrgBouncycastleAsn1CmcTaggedRequest_getInstanceWithId_([s getObjectAtWithInt:t]));
  }
  s = ((LibOrgBouncycastleAsn1ASN1Sequence *) cast_chk([seq getObjectAtWithInt:2], [LibOrgBouncycastleAsn1ASN1Sequence class]));
  self->cmsSequence_ = [IOSObjectArray newArrayWithLength:[((LibOrgBouncycastleAsn1ASN1Sequence *) nil_chk(s)) size] type:LibOrgBouncycastleAsn1CmcTaggedContentInfo_class_()];
  for (jint t = 0; t < self->cmsSequence_->size_; t++) {
    (void) IOSObjectArray_Set(self->cmsSequence_, t, LibOrgBouncycastleAsn1CmcTaggedContentInfo_getInstanceWithId_([s getObjectAtWithInt:t]));
  }
  s = ((LibOrgBouncycastleAsn1ASN1Sequence *) cast_chk([seq getObjectAtWithInt:3], [LibOrgBouncycastleAsn1ASN1Sequence class]));
  self->otherMsgSequence_ = [IOSObjectArray newArrayWithLength:[((LibOrgBouncycastleAsn1ASN1Sequence *) nil_chk(s)) size] type:LibOrgBouncycastleAsn1CmcOtherMsg_class_()];
  for (jint t = 0; t < self->otherMsgSequence_->size_; t++) {
    (void) IOSObjectArray_Set(self->otherMsgSequence_, t, LibOrgBouncycastleAsn1CmcOtherMsg_getInstanceWithId_([s getObjectAtWithInt:t]));
  }
}

LibOrgBouncycastleAsn1CmcPKIData *new_LibOrgBouncycastleAsn1CmcPKIData_initWithLibOrgBouncycastleAsn1ASN1Sequence_(LibOrgBouncycastleAsn1ASN1Sequence *seq) {
  J2OBJC_NEW_IMPL(LibOrgBouncycastleAsn1CmcPKIData, initWithLibOrgBouncycastleAsn1ASN1Sequence_, seq)
}

LibOrgBouncycastleAsn1CmcPKIData *create_LibOrgBouncycastleAsn1CmcPKIData_initWithLibOrgBouncycastleAsn1ASN1Sequence_(LibOrgBouncycastleAsn1ASN1Sequence *seq) {
  J2OBJC_CREATE_IMPL(LibOrgBouncycastleAsn1CmcPKIData, initWithLibOrgBouncycastleAsn1ASN1Sequence_, seq)
}

LibOrgBouncycastleAsn1CmcPKIData *LibOrgBouncycastleAsn1CmcPKIData_getInstanceWithId_(id src) {
  LibOrgBouncycastleAsn1CmcPKIData_initialize();
  if ([src isKindOfClass:[LibOrgBouncycastleAsn1CmcPKIData class]]) {
    return (LibOrgBouncycastleAsn1CmcPKIData *) src;
  }
  if (src != nil) {
    return new_LibOrgBouncycastleAsn1CmcPKIData_initWithLibOrgBouncycastleAsn1ASN1Sequence_(LibOrgBouncycastleAsn1ASN1Sequence_getInstanceWithId_(src));
  }
  return nil;
}

IOSObjectArray *LibOrgBouncycastleAsn1CmcPKIData_copy__WithLibOrgBouncycastleAsn1CmcTaggedAttributeArray_(LibOrgBouncycastleAsn1CmcPKIData *self, IOSObjectArray *taggedAtts) {
  IOSObjectArray *tmp = [IOSObjectArray newArrayWithLength:((IOSObjectArray *) nil_chk(taggedAtts))->size_ type:LibOrgBouncycastleAsn1CmcTaggedAttribute_class_()];
  JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(taggedAtts, 0, tmp, 0, tmp->size_);
  return tmp;
}

IOSObjectArray *LibOrgBouncycastleAsn1CmcPKIData_copy__WithLibOrgBouncycastleAsn1CmcTaggedRequestArray_(LibOrgBouncycastleAsn1CmcPKIData *self, IOSObjectArray *taggedReqs) {
  IOSObjectArray *tmp = [IOSObjectArray newArrayWithLength:((IOSObjectArray *) nil_chk(taggedReqs))->size_ type:LibOrgBouncycastleAsn1CmcTaggedRequest_class_()];
  JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(taggedReqs, 0, tmp, 0, tmp->size_);
  return tmp;
}

IOSObjectArray *LibOrgBouncycastleAsn1CmcPKIData_copy__WithLibOrgBouncycastleAsn1CmcTaggedContentInfoArray_(LibOrgBouncycastleAsn1CmcPKIData *self, IOSObjectArray *taggedConts) {
  IOSObjectArray *tmp = [IOSObjectArray newArrayWithLength:((IOSObjectArray *) nil_chk(taggedConts))->size_ type:LibOrgBouncycastleAsn1CmcTaggedContentInfo_class_()];
  JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(taggedConts, 0, tmp, 0, tmp->size_);
  return tmp;
}

IOSObjectArray *LibOrgBouncycastleAsn1CmcPKIData_copy__WithLibOrgBouncycastleAsn1CmcOtherMsgArray_(LibOrgBouncycastleAsn1CmcPKIData *self, IOSObjectArray *otherMsgs) {
  IOSObjectArray *tmp = [IOSObjectArray newArrayWithLength:((IOSObjectArray *) nil_chk(otherMsgs))->size_ type:LibOrgBouncycastleAsn1CmcOtherMsg_class_()];
  JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(otherMsgs, 0, tmp, 0, tmp->size_);
  return tmp;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(LibOrgBouncycastleAsn1CmcPKIData)
