//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/pqc/asn1/PqcAsn1XMSSPrivateKey.java
//

#ifndef PqcAsn1XMSSPrivateKey_H
#define PqcAsn1XMSSPrivateKey_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "ASN1Object.h"
#include "J2ObjC_header.h"

@class IOSByteArray;
@class LibOrgBouncycastleAsn1ASN1Primitive;

@interface LibOrgBouncycastlePqcAsn1PqcAsn1XMSSPrivateKey : LibOrgBouncycastleAsn1ASN1Object

#pragma mark Public

- (instancetype __nonnull)initWithInt:(jint)index
                        withByteArray:(IOSByteArray *)secretKeySeed
                        withByteArray:(IOSByteArray *)secretKeyPRF
                        withByteArray:(IOSByteArray *)publicSeed
                        withByteArray:(IOSByteArray *)root
                        withByteArray:(IOSByteArray *)bdsState;

- (IOSByteArray *)getBdsState;

- (jint)getIndex;

+ (LibOrgBouncycastlePqcAsn1PqcAsn1XMSSPrivateKey *)getInstanceWithId:(id)o;

- (IOSByteArray *)getPublicSeed;

- (IOSByteArray *)getRoot;

- (IOSByteArray *)getSecretKeyPRF;

- (IOSByteArray *)getSecretKeySeed;

- (LibOrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(LibOrgBouncycastlePqcAsn1PqcAsn1XMSSPrivateKey)

FOUNDATION_EXPORT void LibOrgBouncycastlePqcAsn1PqcAsn1XMSSPrivateKey_initWithInt_withByteArray_withByteArray_withByteArray_withByteArray_withByteArray_(LibOrgBouncycastlePqcAsn1PqcAsn1XMSSPrivateKey *self, jint index, IOSByteArray *secretKeySeed, IOSByteArray *secretKeyPRF, IOSByteArray *publicSeed, IOSByteArray *root, IOSByteArray *bdsState);

FOUNDATION_EXPORT LibOrgBouncycastlePqcAsn1PqcAsn1XMSSPrivateKey *new_LibOrgBouncycastlePqcAsn1PqcAsn1XMSSPrivateKey_initWithInt_withByteArray_withByteArray_withByteArray_withByteArray_withByteArray_(jint index, IOSByteArray *secretKeySeed, IOSByteArray *secretKeyPRF, IOSByteArray *publicSeed, IOSByteArray *root, IOSByteArray *bdsState) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT LibOrgBouncycastlePqcAsn1PqcAsn1XMSSPrivateKey *create_LibOrgBouncycastlePqcAsn1PqcAsn1XMSSPrivateKey_initWithInt_withByteArray_withByteArray_withByteArray_withByteArray_withByteArray_(jint index, IOSByteArray *secretKeySeed, IOSByteArray *secretKeyPRF, IOSByteArray *publicSeed, IOSByteArray *root, IOSByteArray *bdsState);

FOUNDATION_EXPORT LibOrgBouncycastlePqcAsn1PqcAsn1XMSSPrivateKey *LibOrgBouncycastlePqcAsn1PqcAsn1XMSSPrivateKey_getInstanceWithId_(id o);

J2OBJC_TYPE_LITERAL_HEADER(LibOrgBouncycastlePqcAsn1PqcAsn1XMSSPrivateKey)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // PqcAsn1XMSSPrivateKey_H
