//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/pqc/jcajce/provider/mceliece/PqcJcajceMcElieceCCA2Primitives.java
//

#include "BCMcElieceCCA2PrivateKey.h"
#include "BCMcElieceCCA2PublicKey.h"
#include "GF2Matrix.h"
#include "GF2Vector.h"
#include "GF2mField.h"
#include "GoppaCode.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "McElieceCCA2PrivateKeyParameters.h"
#include "McElieceCCA2PublicKeyParameters.h"
#include "Permutation.h"
#include "PolynomialGF2mSmallM.h"
#include "PqcJcajceMcElieceCCA2Primitives.h"
#include "Vector.h"

@interface LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives ()

- (instancetype)init;

@end

__attribute__((unused)) static void LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives_init(LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives *self);

__attribute__((unused)) static LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives *new_LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives *create_LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives_init(void);

@implementation LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *)encryptionPrimitiveWithLibOrgBouncycastlePqcJcajceProviderMcelieceBCMcElieceCCA2PublicKey:(LibOrgBouncycastlePqcJcajceProviderMcelieceBCMcElieceCCA2PublicKey *)pubKey
                                                                                           withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector:(LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *)m
                                                                                           withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector:(LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *)z {
  return LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives_encryptionPrimitiveWithLibOrgBouncycastlePqcJcajceProviderMcelieceBCMcElieceCCA2PublicKey_withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector_withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector_(pubKey, m, z);
}

+ (LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *)encryptionPrimitiveWithLibOrgBouncycastlePqcCryptoMcelieceMcElieceCCA2PublicKeyParameters:(LibOrgBouncycastlePqcCryptoMcelieceMcElieceCCA2PublicKeyParameters *)pubKey
                                                                                           withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector:(LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *)m
                                                                                           withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector:(LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *)z {
  return LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives_encryptionPrimitiveWithLibOrgBouncycastlePqcCryptoMcelieceMcElieceCCA2PublicKeyParameters_withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector_withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector_(pubKey, m, z);
}

+ (IOSObjectArray *)decryptionPrimitiveWithLibOrgBouncycastlePqcJcajceProviderMcelieceBCMcElieceCCA2PrivateKey:(LibOrgBouncycastlePqcJcajceProviderMcelieceBCMcElieceCCA2PrivateKey *)privKey
                                                           withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector:(LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *)c {
  return LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives_decryptionPrimitiveWithLibOrgBouncycastlePqcJcajceProviderMcelieceBCMcElieceCCA2PrivateKey_withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector_(privKey, c);
}

+ (IOSObjectArray *)decryptionPrimitiveWithLibOrgBouncycastlePqcCryptoMcelieceMcElieceCCA2PrivateKeyParameters:(LibOrgBouncycastlePqcCryptoMcelieceMcElieceCCA2PrivateKeyParameters *)privKey
                                                           withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector:(LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *)c {
  return LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives_decryptionPrimitiveWithLibOrgBouncycastlePqcCryptoMcelieceMcElieceCCA2PrivateKeyParameters_withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector_(privKey, c);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LLibOrgBouncycastlePqcMathLinearalgebraGF2Vector;", 0x9, 0, 1, -1, -1, -1, -1 },
    { NULL, "LLibOrgBouncycastlePqcMathLinearalgebraGF2Vector;", 0x9, 0, 2, -1, -1, -1, -1 },
    { NULL, "[LLibOrgBouncycastlePqcMathLinearalgebraGF2Vector;", 0x9, 3, 4, -1, -1, -1, -1 },
    { NULL, "[LLibOrgBouncycastlePqcMathLinearalgebraGF2Vector;", 0x9, 3, 5, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(encryptionPrimitiveWithLibOrgBouncycastlePqcJcajceProviderMcelieceBCMcElieceCCA2PublicKey:withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector:withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector:);
  methods[2].selector = @selector(encryptionPrimitiveWithLibOrgBouncycastlePqcCryptoMcelieceMcElieceCCA2PublicKeyParameters:withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector:withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector:);
  methods[3].selector = @selector(decryptionPrimitiveWithLibOrgBouncycastlePqcJcajceProviderMcelieceBCMcElieceCCA2PrivateKey:withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector:);
  methods[4].selector = @selector(decryptionPrimitiveWithLibOrgBouncycastlePqcCryptoMcelieceMcElieceCCA2PrivateKeyParameters:withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "encryptionPrimitive", "LLibOrgBouncycastlePqcJcajceProviderMcelieceBCMcElieceCCA2PublicKey;LLibOrgBouncycastlePqcMathLinearalgebraGF2Vector;LLibOrgBouncycastlePqcMathLinearalgebraGF2Vector;", "LLibOrgBouncycastlePqcCryptoMcelieceMcElieceCCA2PublicKeyParameters;LLibOrgBouncycastlePqcMathLinearalgebraGF2Vector;LLibOrgBouncycastlePqcMathLinearalgebraGF2Vector;", "decryptionPrimitive", "LLibOrgBouncycastlePqcJcajceProviderMcelieceBCMcElieceCCA2PrivateKey;LLibOrgBouncycastlePqcMathLinearalgebraGF2Vector;", "LLibOrgBouncycastlePqcCryptoMcelieceMcElieceCCA2PrivateKeyParameters;LLibOrgBouncycastlePqcMathLinearalgebraGF2Vector;" };
  static const J2ObjcClassInfo _LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives = { "PqcJcajceMcElieceCCA2Primitives", "lib.org.bouncycastle.pqc.jcajce.provider.mceliece", ptrTable, methods, NULL, 7, 0x11, 5, 0, -1, -1, -1, -1, -1 };
  return &_LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives;
}

@end

void LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives_init(LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives *self) {
  NSObject_init(self);
}

LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives *new_LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives_init() {
  J2OBJC_NEW_IMPL(LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives, init)
}

LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives *create_LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives_init() {
  J2OBJC_CREATE_IMPL(LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives, init)
}

LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives_encryptionPrimitiveWithLibOrgBouncycastlePqcJcajceProviderMcelieceBCMcElieceCCA2PublicKey_withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector_withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector_(LibOrgBouncycastlePqcJcajceProviderMcelieceBCMcElieceCCA2PublicKey *pubKey, LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *m, LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *z) {
  LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives_initialize();
  LibOrgBouncycastlePqcMathLinearalgebraGF2Matrix *matrixG = [((LibOrgBouncycastlePqcJcajceProviderMcelieceBCMcElieceCCA2PublicKey *) nil_chk(pubKey)) getG];
  LibOrgBouncycastlePqcMathLinearalgebraVector *mG = [((LibOrgBouncycastlePqcMathLinearalgebraGF2Matrix *) nil_chk(matrixG)) leftMultiplyLeftCompactFormWithLibOrgBouncycastlePqcMathLinearalgebraVector:m];
  return (LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) cast_chk([((LibOrgBouncycastlePqcMathLinearalgebraVector *) nil_chk(mG)) addWithLibOrgBouncycastlePqcMathLinearalgebraVector:z], [LibOrgBouncycastlePqcMathLinearalgebraGF2Vector class]);
}

LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives_encryptionPrimitiveWithLibOrgBouncycastlePqcCryptoMcelieceMcElieceCCA2PublicKeyParameters_withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector_withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector_(LibOrgBouncycastlePqcCryptoMcelieceMcElieceCCA2PublicKeyParameters *pubKey, LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *m, LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *z) {
  LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives_initialize();
  LibOrgBouncycastlePqcMathLinearalgebraGF2Matrix *matrixG = [((LibOrgBouncycastlePqcCryptoMcelieceMcElieceCCA2PublicKeyParameters *) nil_chk(pubKey)) getG];
  LibOrgBouncycastlePqcMathLinearalgebraVector *mG = [((LibOrgBouncycastlePqcMathLinearalgebraGF2Matrix *) nil_chk(matrixG)) leftMultiplyLeftCompactFormWithLibOrgBouncycastlePqcMathLinearalgebraVector:m];
  return (LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) cast_chk([((LibOrgBouncycastlePqcMathLinearalgebraVector *) nil_chk(mG)) addWithLibOrgBouncycastlePqcMathLinearalgebraVector:z], [LibOrgBouncycastlePqcMathLinearalgebraGF2Vector class]);
}

IOSObjectArray *LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives_decryptionPrimitiveWithLibOrgBouncycastlePqcJcajceProviderMcelieceBCMcElieceCCA2PrivateKey_withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector_(LibOrgBouncycastlePqcJcajceProviderMcelieceBCMcElieceCCA2PrivateKey *privKey, LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *c) {
  LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives_initialize();
  jint k = [((LibOrgBouncycastlePqcJcajceProviderMcelieceBCMcElieceCCA2PrivateKey *) nil_chk(privKey)) getK];
  LibOrgBouncycastlePqcMathLinearalgebraPermutation *p = [privKey getP];
  LibOrgBouncycastlePqcMathLinearalgebraGF2mField *field = [privKey getField];
  LibOrgBouncycastlePqcMathLinearalgebraPolynomialGF2mSmallM *gp = [privKey getGoppaPoly];
  LibOrgBouncycastlePqcMathLinearalgebraGF2Matrix *h = [privKey getH];
  IOSObjectArray *q = [privKey getQInv];
  LibOrgBouncycastlePqcMathLinearalgebraPermutation *pInv = [((LibOrgBouncycastlePqcMathLinearalgebraPermutation *) nil_chk(p)) computeInverse];
  LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *cPInv = (LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) cast_chk([((LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) nil_chk(c)) multiplyWithLibOrgBouncycastlePqcMathLinearalgebraPermutation:pInv], [LibOrgBouncycastlePqcMathLinearalgebraGF2Vector class]);
  LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *syndVec = (LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) cast_chk([((LibOrgBouncycastlePqcMathLinearalgebraGF2Matrix *) nil_chk(h)) rightMultiplyWithLibOrgBouncycastlePqcMathLinearalgebraVector:cPInv], [LibOrgBouncycastlePqcMathLinearalgebraGF2Vector class]);
  LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *errors = LibOrgBouncycastlePqcMathLinearalgebraGoppaCode_syndromeDecodeWithLibOrgBouncycastlePqcMathLinearalgebraGF2Vector_withLibOrgBouncycastlePqcMathLinearalgebraGF2mField_withLibOrgBouncycastlePqcMathLinearalgebraPolynomialGF2mSmallM_withLibOrgBouncycastlePqcMathLinearalgebraPolynomialGF2mSmallMArray_(syndVec, field, gp, q);
  LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *mG = (LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) cast_chk([((LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) nil_chk(cPInv)) addWithLibOrgBouncycastlePqcMathLinearalgebraVector:errors], [LibOrgBouncycastlePqcMathLinearalgebraGF2Vector class]);
  mG = (LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) cast_chk([((LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) nil_chk(mG)) multiplyWithLibOrgBouncycastlePqcMathLinearalgebraPermutation:p], [LibOrgBouncycastlePqcMathLinearalgebraGF2Vector class]);
  errors = (LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) cast_chk([((LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) nil_chk(errors)) multiplyWithLibOrgBouncycastlePqcMathLinearalgebraPermutation:p], [LibOrgBouncycastlePqcMathLinearalgebraGF2Vector class]);
  LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *m = [((LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) nil_chk(mG)) extractRightVectorWithInt:k];
  return [IOSObjectArray newArrayWithObjects:(id[]){ m, errors } count:2 type:LibOrgBouncycastlePqcMathLinearalgebraGF2Vector_class_()];
}

IOSObjectArray *LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives_decryptionPrimitiveWithLibOrgBouncycastlePqcCryptoMcelieceMcElieceCCA2PrivateKeyParameters_withLibOrgBouncycastlePqcMathLinearalgebraGF2Vector_(LibOrgBouncycastlePqcCryptoMcelieceMcElieceCCA2PrivateKeyParameters *privKey, LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *c) {
  LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives_initialize();
  jint k = [((LibOrgBouncycastlePqcCryptoMcelieceMcElieceCCA2PrivateKeyParameters *) nil_chk(privKey)) getK];
  LibOrgBouncycastlePqcMathLinearalgebraPermutation *p = [privKey getP];
  LibOrgBouncycastlePqcMathLinearalgebraGF2mField *field = [privKey getField];
  LibOrgBouncycastlePqcMathLinearalgebraPolynomialGF2mSmallM *gp = [privKey getGoppaPoly];
  LibOrgBouncycastlePqcMathLinearalgebraGF2Matrix *h = [privKey getH];
  IOSObjectArray *q = [privKey getQInv];
  LibOrgBouncycastlePqcMathLinearalgebraPermutation *pInv = [((LibOrgBouncycastlePqcMathLinearalgebraPermutation *) nil_chk(p)) computeInverse];
  LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *cPInv = (LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) cast_chk([((LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) nil_chk(c)) multiplyWithLibOrgBouncycastlePqcMathLinearalgebraPermutation:pInv], [LibOrgBouncycastlePqcMathLinearalgebraGF2Vector class]);
  LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *syndVec = (LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) cast_chk([((LibOrgBouncycastlePqcMathLinearalgebraGF2Matrix *) nil_chk(h)) rightMultiplyWithLibOrgBouncycastlePqcMathLinearalgebraVector:cPInv], [LibOrgBouncycastlePqcMathLinearalgebraGF2Vector class]);
  LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *errors = LibOrgBouncycastlePqcMathLinearalgebraGoppaCode_syndromeDecodeWithLibOrgBouncycastlePqcMathLinearalgebraGF2Vector_withLibOrgBouncycastlePqcMathLinearalgebraGF2mField_withLibOrgBouncycastlePqcMathLinearalgebraPolynomialGF2mSmallM_withLibOrgBouncycastlePqcMathLinearalgebraPolynomialGF2mSmallMArray_(syndVec, field, gp, q);
  LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *mG = (LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) cast_chk([((LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) nil_chk(cPInv)) addWithLibOrgBouncycastlePqcMathLinearalgebraVector:errors], [LibOrgBouncycastlePqcMathLinearalgebraGF2Vector class]);
  mG = (LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) cast_chk([((LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) nil_chk(mG)) multiplyWithLibOrgBouncycastlePqcMathLinearalgebraPermutation:p], [LibOrgBouncycastlePqcMathLinearalgebraGF2Vector class]);
  errors = (LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) cast_chk([((LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) nil_chk(errors)) multiplyWithLibOrgBouncycastlePqcMathLinearalgebraPermutation:p], [LibOrgBouncycastlePqcMathLinearalgebraGF2Vector class]);
  LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *m = [((LibOrgBouncycastlePqcMathLinearalgebraGF2Vector *) nil_chk(mG)) extractRightVectorWithInt:k];
  return [IOSObjectArray newArrayWithObjects:(id[]){ m, errors } count:2 type:LibOrgBouncycastlePqcMathLinearalgebraGF2Vector_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(LibOrgBouncycastlePqcJcajceProviderMceliecePqcJcajceMcElieceCCA2Primitives)
