//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/pqc/crypto/rainbow/RainbowPublicKeyParameters.java
//

#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "RainbowKeyParameters.h"
#include "RainbowPublicKeyParameters.h"

@interface LibOrgBouncycastlePqcCryptoRainbowRainbowPublicKeyParameters () {
 @public
  IOSObjectArray *coeffquadratic_;
  IOSObjectArray *coeffsingular_;
  IOSShortArray *coeffscalar_;
}

@end

J2OBJC_FIELD_SETTER(LibOrgBouncycastlePqcCryptoRainbowRainbowPublicKeyParameters, coeffquadratic_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(LibOrgBouncycastlePqcCryptoRainbowRainbowPublicKeyParameters, coeffsingular_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(LibOrgBouncycastlePqcCryptoRainbowRainbowPublicKeyParameters, coeffscalar_, IOSShortArray *)

@implementation LibOrgBouncycastlePqcCryptoRainbowRainbowPublicKeyParameters

- (instancetype)initWithInt:(jint)docLength
            withShortArray2:(IOSObjectArray *)coeffQuadratic
            withShortArray2:(IOSObjectArray *)coeffSingular
             withShortArray:(IOSShortArray *)coeffScalar {
  LibOrgBouncycastlePqcCryptoRainbowRainbowPublicKeyParameters_initWithInt_withShortArray2_withShortArray2_withShortArray_(self, docLength, coeffQuadratic, coeffSingular, coeffScalar);
  return self;
}

- (IOSObjectArray *)getCoeffQuadratic {
  return coeffquadratic_;
}

- (IOSObjectArray *)getCoeffSingular {
  return coeffsingular_;
}

- (IOSShortArray *)getCoeffScalar {
  return coeffscalar_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "[[S", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[[S", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[S", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithInt:withShortArray2:withShortArray2:withShortArray:);
  methods[1].selector = @selector(getCoeffQuadratic);
  methods[2].selector = @selector(getCoeffSingular);
  methods[3].selector = @selector(getCoeffScalar);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "coeffquadratic_", "[[S", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "coeffsingular_", "[[S", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "coeffscalar_", "[S", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "I[[S[[S[S" };
  static const J2ObjcClassInfo _LibOrgBouncycastlePqcCryptoRainbowRainbowPublicKeyParameters = { "RainbowPublicKeyParameters", "lib.org.bouncycastle.pqc.crypto.rainbow", ptrTable, methods, fields, 7, 0x1, 4, 3, -1, -1, -1, -1, -1 };
  return &_LibOrgBouncycastlePqcCryptoRainbowRainbowPublicKeyParameters;
}

@end

void LibOrgBouncycastlePqcCryptoRainbowRainbowPublicKeyParameters_initWithInt_withShortArray2_withShortArray2_withShortArray_(LibOrgBouncycastlePqcCryptoRainbowRainbowPublicKeyParameters *self, jint docLength, IOSObjectArray *coeffQuadratic, IOSObjectArray *coeffSingular, IOSShortArray *coeffScalar) {
  LibOrgBouncycastlePqcCryptoRainbowRainbowKeyParameters_initWithBoolean_withInt_(self, false, docLength);
  self->coeffquadratic_ = coeffQuadratic;
  self->coeffsingular_ = coeffSingular;
  self->coeffscalar_ = coeffScalar;
}

LibOrgBouncycastlePqcCryptoRainbowRainbowPublicKeyParameters *new_LibOrgBouncycastlePqcCryptoRainbowRainbowPublicKeyParameters_initWithInt_withShortArray2_withShortArray2_withShortArray_(jint docLength, IOSObjectArray *coeffQuadratic, IOSObjectArray *coeffSingular, IOSShortArray *coeffScalar) {
  J2OBJC_NEW_IMPL(LibOrgBouncycastlePqcCryptoRainbowRainbowPublicKeyParameters, initWithInt_withShortArray2_withShortArray2_withShortArray_, docLength, coeffQuadratic, coeffSingular, coeffScalar)
}

LibOrgBouncycastlePqcCryptoRainbowRainbowPublicKeyParameters *create_LibOrgBouncycastlePqcCryptoRainbowRainbowPublicKeyParameters_initWithInt_withShortArray2_withShortArray2_withShortArray_(jint docLength, IOSObjectArray *coeffQuadratic, IOSObjectArray *coeffSingular, IOSShortArray *coeffScalar) {
  J2OBJC_CREATE_IMPL(LibOrgBouncycastlePqcCryptoRainbowRainbowPublicKeyParameters, initWithInt_withShortArray2_withShortArray2_withShortArray_, docLength, coeffQuadratic, coeffSingular, coeffScalar)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(LibOrgBouncycastlePqcCryptoRainbowRainbowPublicKeyParameters)
