//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/bcpg/sig/RevocationReasonTags.java
//

#include "J2ObjC_source.h"
#include "RevocationReasonTags.h"

@implementation LibOrgBouncycastleBcpgSigRevocationReasonTags

+ (jbyte)NO_REASON {
  return LibOrgBouncycastleBcpgSigRevocationReasonTags_NO_REASON;
}

+ (jbyte)KEY_SUPERSEDED {
  return LibOrgBouncycastleBcpgSigRevocationReasonTags_KEY_SUPERSEDED;
}

+ (jbyte)KEY_COMPROMISED {
  return LibOrgBouncycastleBcpgSigRevocationReasonTags_KEY_COMPROMISED;
}

+ (jbyte)KEY_RETIRED {
  return LibOrgBouncycastleBcpgSigRevocationReasonTags_KEY_RETIRED;
}

+ (jbyte)USER_NO_LONGER_VALID {
  return LibOrgBouncycastleBcpgSigRevocationReasonTags_USER_NO_LONGER_VALID;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcFieldInfo fields[] = {
    { "NO_REASON", "B", .constantValue.asChar = LibOrgBouncycastleBcpgSigRevocationReasonTags_NO_REASON, 0x19, -1, -1, -1, -1 },
    { "KEY_SUPERSEDED", "B", .constantValue.asChar = LibOrgBouncycastleBcpgSigRevocationReasonTags_KEY_SUPERSEDED, 0x19, -1, -1, -1, -1 },
    { "KEY_COMPROMISED", "B", .constantValue.asChar = LibOrgBouncycastleBcpgSigRevocationReasonTags_KEY_COMPROMISED, 0x19, -1, -1, -1, -1 },
    { "KEY_RETIRED", "B", .constantValue.asChar = LibOrgBouncycastleBcpgSigRevocationReasonTags_KEY_RETIRED, 0x19, -1, -1, -1, -1 },
    { "USER_NO_LONGER_VALID", "B", .constantValue.asChar = LibOrgBouncycastleBcpgSigRevocationReasonTags_USER_NO_LONGER_VALID, 0x19, -1, -1, -1, -1 },
  };
  static const J2ObjcClassInfo _LibOrgBouncycastleBcpgSigRevocationReasonTags = { "RevocationReasonTags", "lib.org.bouncycastle.bcpg.sig", NULL, NULL, fields, 7, 0x609, 0, 5, -1, -1, -1, -1, -1 };
  return &_LibOrgBouncycastleBcpgSigRevocationReasonTags;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(LibOrgBouncycastleBcpgSigRevocationReasonTags)
