//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/crypto/generators/RSABlindingFactorGenerator.java
//

#ifndef RSABlindingFactorGenerator_H
#define RSABlindingFactorGenerator_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@class JavaMathBigInteger;
@protocol LibOrgBouncycastleCryptoCipherParameters;

@interface LibOrgBouncycastleCryptoGeneratorsRSABlindingFactorGenerator : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

- (JavaMathBigInteger *)generateBlindingFactor;

- (void)init__WithLibOrgBouncycastleCryptoCipherParameters:(id<LibOrgBouncycastleCryptoCipherParameters>)param OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_STATIC_INIT(LibOrgBouncycastleCryptoGeneratorsRSABlindingFactorGenerator)

FOUNDATION_EXPORT void LibOrgBouncycastleCryptoGeneratorsRSABlindingFactorGenerator_init(LibOrgBouncycastleCryptoGeneratorsRSABlindingFactorGenerator *self);

FOUNDATION_EXPORT LibOrgBouncycastleCryptoGeneratorsRSABlindingFactorGenerator *new_LibOrgBouncycastleCryptoGeneratorsRSABlindingFactorGenerator_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT LibOrgBouncycastleCryptoGeneratorsRSABlindingFactorGenerator *create_LibOrgBouncycastleCryptoGeneratorsRSABlindingFactorGenerator_init(void);

J2OBJC_TYPE_LITERAL_HEADER(LibOrgBouncycastleCryptoGeneratorsRSABlindingFactorGenerator)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // RSABlindingFactorGenerator_H
