//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/math/ec/custom/sec/SecP224R1Curve.java
//

#include "ECCurve.h"
#include "ECFieldElement.h"
#include "ECLookupTable.h"
#include "ECPoint.h"
#include "Hex.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "Nat224.h"
#include "SecP224R1Curve.h"
#include "SecP224R1FieldElement.h"
#include "SecP224R1Point.h"
#include "java/math/BigInteger.h"

inline jint LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_get_SecP224R1_DEFAULT_COORDS(void);
#define LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_SecP224R1_DEFAULT_COORDS 2
J2OBJC_STATIC_FIELD_CONSTANT(LibOrgBouncycastleMathEcCustomSecSecP224R1Curve, SecP224R1_DEFAULT_COORDS, jint)

@interface LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_1 : NSObject < LibOrgBouncycastleMathEcECLookupTable > {
 @public
  LibOrgBouncycastleMathEcCustomSecSecP224R1Curve *this$0_;
  jint val$len_;
  IOSIntArray *val$table_;
}

- (instancetype)initWithLibOrgBouncycastleMathEcCustomSecSecP224R1Curve:(LibOrgBouncycastleMathEcCustomSecSecP224R1Curve *)outer$
                                                                withInt:(jint)capture$0
                                                           withIntArray:(IOSIntArray *)capture$1;

- (jint)getSize;

- (LibOrgBouncycastleMathEcECPoint *)lookupWithInt:(jint)index;

@end

J2OBJC_EMPTY_STATIC_INIT(LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_1)

__attribute__((unused)) static void LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_1_initWithLibOrgBouncycastleMathEcCustomSecSecP224R1Curve_withInt_withIntArray_(LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_1 *self, LibOrgBouncycastleMathEcCustomSecSecP224R1Curve *outer$, jint capture$0, IOSIntArray *capture$1);

__attribute__((unused)) static LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_1 *new_LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_1_initWithLibOrgBouncycastleMathEcCustomSecSecP224R1Curve_withInt_withIntArray_(LibOrgBouncycastleMathEcCustomSecSecP224R1Curve *outer$, jint capture$0, IOSIntArray *capture$1) NS_RETURNS_RETAINED;

__attribute__((unused)) static LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_1 *create_LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_1_initWithLibOrgBouncycastleMathEcCustomSecSecP224R1Curve_withInt_withIntArray_(LibOrgBouncycastleMathEcCustomSecSecP224R1Curve *outer$, jint capture$0, IOSIntArray *capture$1);

J2OBJC_INITIALIZED_DEFN(LibOrgBouncycastleMathEcCustomSecSecP224R1Curve)

JavaMathBigInteger *LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_q;

@implementation LibOrgBouncycastleMathEcCustomSecSecP224R1Curve

+ (JavaMathBigInteger *)q {
  return LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_q;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (LibOrgBouncycastleMathEcECCurve *)cloneCurve {
  return new_LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_init();
}

- (jboolean)supportsCoordinateSystemWithInt:(jint)coord {
  switch (coord) {
    case LibOrgBouncycastleMathEcECCurve_COORD_JACOBIAN:
    return true;
    default:
    return false;
  }
}

- (JavaMathBigInteger *)getQ {
  return LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_q;
}

- (jint)getFieldSize {
  return [((JavaMathBigInteger *) nil_chk(LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_q)) bitLength];
}

- (LibOrgBouncycastleMathEcECFieldElement *)fromBigIntegerWithJavaMathBigInteger:(JavaMathBigInteger *)x {
  return new_LibOrgBouncycastleMathEcCustomSecSecP224R1FieldElement_initWithJavaMathBigInteger_(x);
}

- (LibOrgBouncycastleMathEcECPoint *)createRawPointWithLibOrgBouncycastleMathEcECFieldElement:(LibOrgBouncycastleMathEcECFieldElement *)x
                                                   withLibOrgBouncycastleMathEcECFieldElement:(LibOrgBouncycastleMathEcECFieldElement *)y
                                                                                  withBoolean:(jboolean)withCompression {
  return new_LibOrgBouncycastleMathEcCustomSecSecP224R1Point_initWithLibOrgBouncycastleMathEcECCurve_withLibOrgBouncycastleMathEcECFieldElement_withLibOrgBouncycastleMathEcECFieldElement_withBoolean_(self, x, y, withCompression);
}

- (LibOrgBouncycastleMathEcECPoint *)createRawPointWithLibOrgBouncycastleMathEcECFieldElement:(LibOrgBouncycastleMathEcECFieldElement *)x
                                                   withLibOrgBouncycastleMathEcECFieldElement:(LibOrgBouncycastleMathEcECFieldElement *)y
                                              withLibOrgBouncycastleMathEcECFieldElementArray:(IOSObjectArray *)zs
                                                                                  withBoolean:(jboolean)withCompression {
  return new_LibOrgBouncycastleMathEcCustomSecSecP224R1Point_initWithLibOrgBouncycastleMathEcECCurve_withLibOrgBouncycastleMathEcECFieldElement_withLibOrgBouncycastleMathEcECFieldElement_withLibOrgBouncycastleMathEcECFieldElementArray_withBoolean_(self, x, y, zs, withCompression);
}

- (LibOrgBouncycastleMathEcECPoint *)getInfinity {
  return infinity_;
}

- (id<LibOrgBouncycastleMathEcECLookupTable>)createCacheSafeLookupTableWithLibOrgBouncycastleMathEcECPointArray:(IOSObjectArray *)points
                                                                                                        withInt:(jint)off
                                                                                                        withInt:(jint)len {
  jint FE_INTS = 7;
  IOSIntArray *table = [IOSIntArray newArrayWithLength:len * FE_INTS * 2];
  {
    jint pos = 0;
    for (jint i = 0; i < len; ++i) {
      LibOrgBouncycastleMathEcECPoint *p = IOSObjectArray_Get(nil_chk(points), off + i);
      LibOrgBouncycastleMathRawNat224_copy__WithIntArray_withInt_withIntArray_withInt_(((LibOrgBouncycastleMathEcCustomSecSecP224R1FieldElement *) nil_chk(((LibOrgBouncycastleMathEcCustomSecSecP224R1FieldElement *) cast_chk([((LibOrgBouncycastleMathEcECPoint *) nil_chk(p)) getRawXCoord], [LibOrgBouncycastleMathEcCustomSecSecP224R1FieldElement class]))))->x_, 0, table, pos);
      pos += FE_INTS;
      LibOrgBouncycastleMathRawNat224_copy__WithIntArray_withInt_withIntArray_withInt_(((LibOrgBouncycastleMathEcCustomSecSecP224R1FieldElement *) nil_chk(((LibOrgBouncycastleMathEcCustomSecSecP224R1FieldElement *) cast_chk([p getRawYCoord], [LibOrgBouncycastleMathEcCustomSecSecP224R1FieldElement class]))))->x_, 0, table, pos);
      pos += FE_INTS;
    }
  }
  return new_LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_1_initWithLibOrgBouncycastleMathEcCustomSecSecP224R1Curve_withInt_withIntArray_(self, len, table);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LLibOrgBouncycastleMathEcECCurve;", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "LJavaMathBigInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LLibOrgBouncycastleMathEcECFieldElement;", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "LLibOrgBouncycastleMathEcECPoint;", 0x4, 4, 5, -1, -1, -1, -1 },
    { NULL, "LLibOrgBouncycastleMathEcECPoint;", 0x4, 4, 6, -1, -1, -1, -1 },
    { NULL, "LLibOrgBouncycastleMathEcECPoint;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LLibOrgBouncycastleMathEcECLookupTable;", 0x1, 7, 8, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(cloneCurve);
  methods[2].selector = @selector(supportsCoordinateSystemWithInt:);
  methods[3].selector = @selector(getQ);
  methods[4].selector = @selector(getFieldSize);
  methods[5].selector = @selector(fromBigIntegerWithJavaMathBigInteger:);
  methods[6].selector = @selector(createRawPointWithLibOrgBouncycastleMathEcECFieldElement:withLibOrgBouncycastleMathEcECFieldElement:withBoolean:);
  methods[7].selector = @selector(createRawPointWithLibOrgBouncycastleMathEcECFieldElement:withLibOrgBouncycastleMathEcECFieldElement:withLibOrgBouncycastleMathEcECFieldElementArray:withBoolean:);
  methods[8].selector = @selector(getInfinity);
  methods[9].selector = @selector(createCacheSafeLookupTableWithLibOrgBouncycastleMathEcECPointArray:withInt:withInt:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "q", "LJavaMathBigInteger;", .constantValue.asLong = 0, 0x19, -1, 9, -1, -1 },
    { "SecP224R1_DEFAULT_COORDS", "I", .constantValue.asInt = LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_SecP224R1_DEFAULT_COORDS, 0x1a, -1, -1, -1, -1 },
    { "infinity_", "LLibOrgBouncycastleMathEcCustomSecSecP224R1Point;", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "supportsCoordinateSystem", "I", "fromBigInteger", "LJavaMathBigInteger;", "createRawPoint", "LLibOrgBouncycastleMathEcECFieldElement;LLibOrgBouncycastleMathEcECFieldElement;Z", "LLibOrgBouncycastleMathEcECFieldElement;LLibOrgBouncycastleMathEcECFieldElement;[LLibOrgBouncycastleMathEcECFieldElement;Z", "createCacheSafeLookupTable", "[LLibOrgBouncycastleMathEcECPoint;II", &LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_q };
  static const J2ObjcClassInfo _LibOrgBouncycastleMathEcCustomSecSecP224R1Curve = { "SecP224R1Curve", "lib.org.bouncycastle.math.ec.custom.sec", ptrTable, methods, fields, 7, 0x1, 10, 3, -1, -1, -1, -1, -1 };
  return &_LibOrgBouncycastleMathEcCustomSecSecP224R1Curve;
}

+ (void)initialize {
  if (self == [LibOrgBouncycastleMathEcCustomSecSecP224R1Curve class]) {
    LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_q = new_JavaMathBigInteger_initWithInt_withByteArray_(1, LibOrgBouncycastleUtilEncodersHex_decodeWithNSString_(@"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000000000000000001"));
    J2OBJC_SET_INITIALIZED(LibOrgBouncycastleMathEcCustomSecSecP224R1Curve)
  }
}

@end

void LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_init(LibOrgBouncycastleMathEcCustomSecSecP224R1Curve *self) {
  LibOrgBouncycastleMathEcECCurve_AbstractFp_initWithJavaMathBigInteger_(self, LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_q);
  self->infinity_ = new_LibOrgBouncycastleMathEcCustomSecSecP224R1Point_initWithLibOrgBouncycastleMathEcECCurve_withLibOrgBouncycastleMathEcECFieldElement_withLibOrgBouncycastleMathEcECFieldElement_(self, nil, nil);
  self->a_ = [self fromBigIntegerWithJavaMathBigInteger:new_JavaMathBigInteger_initWithInt_withByteArray_(1, LibOrgBouncycastleUtilEncodersHex_decodeWithNSString_(@"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFE"))];
  self->b_ = [self fromBigIntegerWithJavaMathBigInteger:new_JavaMathBigInteger_initWithInt_withByteArray_(1, LibOrgBouncycastleUtilEncodersHex_decodeWithNSString_(@"B4050A850C04B3ABF54132565044B0B7D7BFD8BA270B39432355FFB4"))];
  self->order_ = new_JavaMathBigInteger_initWithInt_withByteArray_(1, LibOrgBouncycastleUtilEncodersHex_decodeWithNSString_(@"FFFFFFFFFFFFFFFFFFFFFFFFFFFF16A2E0B8F03E13DD29455C5C2A3D"));
  self->cofactor_ = JavaMathBigInteger_valueOfWithLong_(1);
  self->coord_ = LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_SecP224R1_DEFAULT_COORDS;
}

LibOrgBouncycastleMathEcCustomSecSecP224R1Curve *new_LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_init() {
  J2OBJC_NEW_IMPL(LibOrgBouncycastleMathEcCustomSecSecP224R1Curve, init)
}

LibOrgBouncycastleMathEcCustomSecSecP224R1Curve *create_LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_init() {
  J2OBJC_CREATE_IMPL(LibOrgBouncycastleMathEcCustomSecSecP224R1Curve, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(LibOrgBouncycastleMathEcCustomSecSecP224R1Curve)

@implementation LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_1

- (instancetype)initWithLibOrgBouncycastleMathEcCustomSecSecP224R1Curve:(LibOrgBouncycastleMathEcCustomSecSecP224R1Curve *)outer$
                                                                withInt:(jint)capture$0
                                                           withIntArray:(IOSIntArray *)capture$1 {
  LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_1_initWithLibOrgBouncycastleMathEcCustomSecSecP224R1Curve_withInt_withIntArray_(self, outer$, capture$0, capture$1);
  return self;
}

- (jint)getSize {
  return val$len_;
}

- (LibOrgBouncycastleMathEcECPoint *)lookupWithInt:(jint)index {
  IOSIntArray *x = LibOrgBouncycastleMathRawNat224_create();
  IOSIntArray *y = LibOrgBouncycastleMathRawNat224_create();
  jint pos = 0;
  for (jint i = 0; i < val$len_; ++i) {
    jint MASK = JreRShift32(((i ^ index) - 1), 31);
    for (jint j = 0; j < 7; ++j) {
      *IOSIntArray_GetRef(nil_chk(x), j) ^= IOSIntArray_Get(nil_chk(val$table_), pos + j) & MASK;
      *IOSIntArray_GetRef(nil_chk(y), j) ^= IOSIntArray_Get(val$table_, pos + 7 + j) & MASK;
    }
    pos += (7 * 2);
  }
  return [this$0_ createRawPointWithLibOrgBouncycastleMathEcECFieldElement:new_LibOrgBouncycastleMathEcCustomSecSecP224R1FieldElement_initWithIntArray_(x) withLibOrgBouncycastleMathEcECFieldElement:new_LibOrgBouncycastleMathEcCustomSecSecP224R1FieldElement_initWithIntArray_(y) withBoolean:false];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LLibOrgBouncycastleMathEcECPoint;", 0x1, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithLibOrgBouncycastleMathEcCustomSecSecP224R1Curve:withInt:withIntArray:);
  methods[1].selector = @selector(getSize);
  methods[2].selector = @selector(lookupWithInt:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LLibOrgBouncycastleMathEcCustomSecSecP224R1Curve;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "val$len_", "I", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "val$table_", "[I", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "lookup", "I", "LLibOrgBouncycastleMathEcCustomSecSecP224R1Curve;", "createCacheSafeLookupTableWithLibOrgBouncycastleMathEcECPointArray:withInt:withInt:" };
  static const J2ObjcClassInfo _LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_1 = { "", "lib.org.bouncycastle.math.ec.custom.sec", ptrTable, methods, fields, 7, 0x8010, 3, 3, 2, -1, 3, -1, -1 };
  return &_LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_1;
}

@end

void LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_1_initWithLibOrgBouncycastleMathEcCustomSecSecP224R1Curve_withInt_withIntArray_(LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_1 *self, LibOrgBouncycastleMathEcCustomSecSecP224R1Curve *outer$, jint capture$0, IOSIntArray *capture$1) {
  self->this$0_ = outer$;
  self->val$len_ = capture$0;
  self->val$table_ = capture$1;
  NSObject_init(self);
}

LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_1 *new_LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_1_initWithLibOrgBouncycastleMathEcCustomSecSecP224R1Curve_withInt_withIntArray_(LibOrgBouncycastleMathEcCustomSecSecP224R1Curve *outer$, jint capture$0, IOSIntArray *capture$1) {
  J2OBJC_NEW_IMPL(LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_1, initWithLibOrgBouncycastleMathEcCustomSecSecP224R1Curve_withInt_withIntArray_, outer$, capture$0, capture$1)
}

LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_1 *create_LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_1_initWithLibOrgBouncycastleMathEcCustomSecSecP224R1Curve_withInt_withIntArray_(LibOrgBouncycastleMathEcCustomSecSecP224R1Curve *outer$, jint capture$0, IOSIntArray *capture$1) {
  J2OBJC_CREATE_IMPL(LibOrgBouncycastleMathEcCustomSecSecP224R1Curve_1, initWithLibOrgBouncycastleMathEcCustomSecSecP224R1Curve_withInt_withIntArray_, outer$, capture$0, capture$1)
}
