//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/crypto/SignerWithRecovery.java
//

#include "J2ObjC_source.h"
#include "SignerWithRecovery.h"

@interface LibOrgBouncycastleCryptoSignerWithRecovery : NSObject

@end

@implementation LibOrgBouncycastleCryptoSignerWithRecovery

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "Z", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "[B", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 0, 1, 2, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(hasFullMessage);
  methods[1].selector = @selector(getRecoveredMessage);
  methods[2].selector = @selector(updateWithRecoveredMessageWithByteArray:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "updateWithRecoveredMessage", "[B", "LLibOrgBouncycastleCryptoInvalidCipherTextException;" };
  static const J2ObjcClassInfo _LibOrgBouncycastleCryptoSignerWithRecovery = { "SignerWithRecovery", "lib.org.bouncycastle.crypto", ptrTable, methods, NULL, 7, 0x609, 3, 0, -1, -1, -1, -1, -1 };
  return &_LibOrgBouncycastleCryptoSignerWithRecovery;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(LibOrgBouncycastleCryptoSignerWithRecovery)
