//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/asn1/smime/SMIMECapability.java
//

#include "ASN1Encodable.h"
#include "ASN1EncodableVector.h"
#include "ASN1Object.h"
#include "ASN1ObjectIdentifier.h"
#include "ASN1Primitive.h"
#include "ASN1Sequence.h"
#include "DERSequence.h"
#include "J2ObjC_source.h"
#include "NISTObjectIdentifiers.h"
#include "PKCSObjectIdentifiers.h"
#include "SMIMECapability.h"
#include "java/lang/IllegalArgumentException.h"

@interface LibOrgBouncycastleAsn1SmimeSMIMECapability () {
 @public
  LibOrgBouncycastleAsn1ASN1ObjectIdentifier *capabilityID_;
  id<LibOrgBouncycastleAsn1ASN1Encodable> parameters_;
}

@end

J2OBJC_FIELD_SETTER(LibOrgBouncycastleAsn1SmimeSMIMECapability, capabilityID_, LibOrgBouncycastleAsn1ASN1ObjectIdentifier *)
J2OBJC_FIELD_SETTER(LibOrgBouncycastleAsn1SmimeSMIMECapability, parameters_, id<LibOrgBouncycastleAsn1ASN1Encodable>)

J2OBJC_INITIALIZED_DEFN(LibOrgBouncycastleAsn1SmimeSMIMECapability)

LibOrgBouncycastleAsn1ASN1ObjectIdentifier *LibOrgBouncycastleAsn1SmimeSMIMECapability_preferSignedData;
LibOrgBouncycastleAsn1ASN1ObjectIdentifier *LibOrgBouncycastleAsn1SmimeSMIMECapability_canNotDecryptAny;
LibOrgBouncycastleAsn1ASN1ObjectIdentifier *LibOrgBouncycastleAsn1SmimeSMIMECapability_sMIMECapabilitiesVersions;
LibOrgBouncycastleAsn1ASN1ObjectIdentifier *LibOrgBouncycastleAsn1SmimeSMIMECapability_dES_CBC;
LibOrgBouncycastleAsn1ASN1ObjectIdentifier *LibOrgBouncycastleAsn1SmimeSMIMECapability_dES_EDE3_CBC;
LibOrgBouncycastleAsn1ASN1ObjectIdentifier *LibOrgBouncycastleAsn1SmimeSMIMECapability_rC2_CBC;
LibOrgBouncycastleAsn1ASN1ObjectIdentifier *LibOrgBouncycastleAsn1SmimeSMIMECapability_aES128_CBC;
LibOrgBouncycastleAsn1ASN1ObjectIdentifier *LibOrgBouncycastleAsn1SmimeSMIMECapability_aES192_CBC;
LibOrgBouncycastleAsn1ASN1ObjectIdentifier *LibOrgBouncycastleAsn1SmimeSMIMECapability_aES256_CBC;

@implementation LibOrgBouncycastleAsn1SmimeSMIMECapability

+ (LibOrgBouncycastleAsn1ASN1ObjectIdentifier *)preferSignedData {
  return LibOrgBouncycastleAsn1SmimeSMIMECapability_preferSignedData;
}

+ (LibOrgBouncycastleAsn1ASN1ObjectIdentifier *)canNotDecryptAny {
  return LibOrgBouncycastleAsn1SmimeSMIMECapability_canNotDecryptAny;
}

+ (LibOrgBouncycastleAsn1ASN1ObjectIdentifier *)sMIMECapabilitiesVersions {
  return LibOrgBouncycastleAsn1SmimeSMIMECapability_sMIMECapabilitiesVersions;
}

+ (LibOrgBouncycastleAsn1ASN1ObjectIdentifier *)dES_CBC {
  return LibOrgBouncycastleAsn1SmimeSMIMECapability_dES_CBC;
}

+ (LibOrgBouncycastleAsn1ASN1ObjectIdentifier *)dES_EDE3_CBC {
  return LibOrgBouncycastleAsn1SmimeSMIMECapability_dES_EDE3_CBC;
}

+ (LibOrgBouncycastleAsn1ASN1ObjectIdentifier *)rC2_CBC {
  return LibOrgBouncycastleAsn1SmimeSMIMECapability_rC2_CBC;
}

+ (LibOrgBouncycastleAsn1ASN1ObjectIdentifier *)aES128_CBC {
  return LibOrgBouncycastleAsn1SmimeSMIMECapability_aES128_CBC;
}

+ (LibOrgBouncycastleAsn1ASN1ObjectIdentifier *)aES192_CBC {
  return LibOrgBouncycastleAsn1SmimeSMIMECapability_aES192_CBC;
}

+ (LibOrgBouncycastleAsn1ASN1ObjectIdentifier *)aES256_CBC {
  return LibOrgBouncycastleAsn1SmimeSMIMECapability_aES256_CBC;
}

- (instancetype)initWithLibOrgBouncycastleAsn1ASN1Sequence:(LibOrgBouncycastleAsn1ASN1Sequence *)seq {
  LibOrgBouncycastleAsn1SmimeSMIMECapability_initWithLibOrgBouncycastleAsn1ASN1Sequence_(self, seq);
  return self;
}

- (instancetype)initWithLibOrgBouncycastleAsn1ASN1ObjectIdentifier:(LibOrgBouncycastleAsn1ASN1ObjectIdentifier *)capabilityID
                           withLibOrgBouncycastleAsn1ASN1Encodable:(id<LibOrgBouncycastleAsn1ASN1Encodable>)parameters {
  LibOrgBouncycastleAsn1SmimeSMIMECapability_initWithLibOrgBouncycastleAsn1ASN1ObjectIdentifier_withLibOrgBouncycastleAsn1ASN1Encodable_(self, capabilityID, parameters);
  return self;
}

+ (LibOrgBouncycastleAsn1SmimeSMIMECapability *)getInstanceWithId:(id)obj {
  return LibOrgBouncycastleAsn1SmimeSMIMECapability_getInstanceWithId_(obj);
}

- (LibOrgBouncycastleAsn1ASN1ObjectIdentifier *)getCapabilityID {
  return capabilityID_;
}

- (id<LibOrgBouncycastleAsn1ASN1Encodable>)getParameters {
  return parameters_;
}

- (LibOrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive {
  LibOrgBouncycastleAsn1ASN1EncodableVector *v = new_LibOrgBouncycastleAsn1ASN1EncodableVector_init();
  [v addWithLibOrgBouncycastleAsn1ASN1Encodable:capabilityID_];
  if (parameters_ != nil) {
    [v addWithLibOrgBouncycastleAsn1ASN1Encodable:parameters_];
  }
  return new_LibOrgBouncycastleAsn1DERSequence_initWithLibOrgBouncycastleAsn1ASN1EncodableVector_(v);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, "LLibOrgBouncycastleAsn1SmimeSMIMECapability;", 0x9, 2, 3, -1, -1, -1, -1 },
    { NULL, "LLibOrgBouncycastleAsn1ASN1ObjectIdentifier;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LLibOrgBouncycastleAsn1ASN1Encodable;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LLibOrgBouncycastleAsn1ASN1Primitive;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithLibOrgBouncycastleAsn1ASN1Sequence:);
  methods[1].selector = @selector(initWithLibOrgBouncycastleAsn1ASN1ObjectIdentifier:withLibOrgBouncycastleAsn1ASN1Encodable:);
  methods[2].selector = @selector(getInstanceWithId:);
  methods[3].selector = @selector(getCapabilityID);
  methods[4].selector = @selector(getParameters);
  methods[5].selector = @selector(toASN1Primitive);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "preferSignedData", "LLibOrgBouncycastleAsn1ASN1ObjectIdentifier;", .constantValue.asLong = 0, 0x19, -1, 4, -1, -1 },
    { "canNotDecryptAny", "LLibOrgBouncycastleAsn1ASN1ObjectIdentifier;", .constantValue.asLong = 0, 0x19, -1, 5, -1, -1 },
    { "sMIMECapabilitiesVersions", "LLibOrgBouncycastleAsn1ASN1ObjectIdentifier;", .constantValue.asLong = 0, 0x19, -1, 6, -1, -1 },
    { "dES_CBC", "LLibOrgBouncycastleAsn1ASN1ObjectIdentifier;", .constantValue.asLong = 0, 0x19, -1, 7, -1, -1 },
    { "dES_EDE3_CBC", "LLibOrgBouncycastleAsn1ASN1ObjectIdentifier;", .constantValue.asLong = 0, 0x19, -1, 8, -1, -1 },
    { "rC2_CBC", "LLibOrgBouncycastleAsn1ASN1ObjectIdentifier;", .constantValue.asLong = 0, 0x19, -1, 9, -1, -1 },
    { "aES128_CBC", "LLibOrgBouncycastleAsn1ASN1ObjectIdentifier;", .constantValue.asLong = 0, 0x19, -1, 10, -1, -1 },
    { "aES192_CBC", "LLibOrgBouncycastleAsn1ASN1ObjectIdentifier;", .constantValue.asLong = 0, 0x19, -1, 11, -1, -1 },
    { "aES256_CBC", "LLibOrgBouncycastleAsn1ASN1ObjectIdentifier;", .constantValue.asLong = 0, 0x19, -1, 12, -1, -1 },
    { "capabilityID_", "LLibOrgBouncycastleAsn1ASN1ObjectIdentifier;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "parameters_", "LLibOrgBouncycastleAsn1ASN1Encodable;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LLibOrgBouncycastleAsn1ASN1Sequence;", "LLibOrgBouncycastleAsn1ASN1ObjectIdentifier;LLibOrgBouncycastleAsn1ASN1Encodable;", "getInstance", "LNSObject;", &LibOrgBouncycastleAsn1SmimeSMIMECapability_preferSignedData, &LibOrgBouncycastleAsn1SmimeSMIMECapability_canNotDecryptAny, &LibOrgBouncycastleAsn1SmimeSMIMECapability_sMIMECapabilitiesVersions, &LibOrgBouncycastleAsn1SmimeSMIMECapability_dES_CBC, &LibOrgBouncycastleAsn1SmimeSMIMECapability_dES_EDE3_CBC, &LibOrgBouncycastleAsn1SmimeSMIMECapability_rC2_CBC, &LibOrgBouncycastleAsn1SmimeSMIMECapability_aES128_CBC, &LibOrgBouncycastleAsn1SmimeSMIMECapability_aES192_CBC, &LibOrgBouncycastleAsn1SmimeSMIMECapability_aES256_CBC };
  static const J2ObjcClassInfo _LibOrgBouncycastleAsn1SmimeSMIMECapability = { "SMIMECapability", "lib.org.bouncycastle.asn1.smime", ptrTable, methods, fields, 7, 0x1, 6, 11, -1, -1, -1, -1, -1 };
  return &_LibOrgBouncycastleAsn1SmimeSMIMECapability;
}

+ (void)initialize {
  if (self == [LibOrgBouncycastleAsn1SmimeSMIMECapability class]) {
    LibOrgBouncycastleAsn1SmimeSMIMECapability_preferSignedData = JreLoadStatic(LibOrgBouncycastleAsn1PkcsPKCSObjectIdentifiers, preferSignedData);
    LibOrgBouncycastleAsn1SmimeSMIMECapability_canNotDecryptAny = JreLoadStatic(LibOrgBouncycastleAsn1PkcsPKCSObjectIdentifiers, canNotDecryptAny);
    LibOrgBouncycastleAsn1SmimeSMIMECapability_sMIMECapabilitiesVersions = JreLoadStatic(LibOrgBouncycastleAsn1PkcsPKCSObjectIdentifiers, sMIMECapabilitiesVersions);
    LibOrgBouncycastleAsn1SmimeSMIMECapability_dES_CBC = new_LibOrgBouncycastleAsn1ASN1ObjectIdentifier_initWithNSString_(@"1.3.14.3.2.7");
    LibOrgBouncycastleAsn1SmimeSMIMECapability_dES_EDE3_CBC = JreLoadStatic(LibOrgBouncycastleAsn1PkcsPKCSObjectIdentifiers, des_EDE3_CBC);
    LibOrgBouncycastleAsn1SmimeSMIMECapability_rC2_CBC = JreLoadStatic(LibOrgBouncycastleAsn1PkcsPKCSObjectIdentifiers, RC2_CBC);
    LibOrgBouncycastleAsn1SmimeSMIMECapability_aES128_CBC = JreLoadStatic(LibOrgBouncycastleAsn1NistNISTObjectIdentifiers, id_aes128_CBC);
    LibOrgBouncycastleAsn1SmimeSMIMECapability_aES192_CBC = JreLoadStatic(LibOrgBouncycastleAsn1NistNISTObjectIdentifiers, id_aes192_CBC);
    LibOrgBouncycastleAsn1SmimeSMIMECapability_aES256_CBC = JreLoadStatic(LibOrgBouncycastleAsn1NistNISTObjectIdentifiers, id_aes256_CBC);
    J2OBJC_SET_INITIALIZED(LibOrgBouncycastleAsn1SmimeSMIMECapability)
  }
}

@end

void LibOrgBouncycastleAsn1SmimeSMIMECapability_initWithLibOrgBouncycastleAsn1ASN1Sequence_(LibOrgBouncycastleAsn1SmimeSMIMECapability *self, LibOrgBouncycastleAsn1ASN1Sequence *seq) {
  LibOrgBouncycastleAsn1ASN1Object_init(self);
  self->capabilityID_ = (LibOrgBouncycastleAsn1ASN1ObjectIdentifier *) cast_chk([((LibOrgBouncycastleAsn1ASN1Sequence *) nil_chk(seq)) getObjectAtWithInt:0], [LibOrgBouncycastleAsn1ASN1ObjectIdentifier class]);
  if ([seq size] > 1) {
    self->parameters_ = (LibOrgBouncycastleAsn1ASN1Primitive *) cast_chk([seq getObjectAtWithInt:1], [LibOrgBouncycastleAsn1ASN1Primitive class]);
  }
}

LibOrgBouncycastleAsn1SmimeSMIMECapability *new_LibOrgBouncycastleAsn1SmimeSMIMECapability_initWithLibOrgBouncycastleAsn1ASN1Sequence_(LibOrgBouncycastleAsn1ASN1Sequence *seq) {
  J2OBJC_NEW_IMPL(LibOrgBouncycastleAsn1SmimeSMIMECapability, initWithLibOrgBouncycastleAsn1ASN1Sequence_, seq)
}

LibOrgBouncycastleAsn1SmimeSMIMECapability *create_LibOrgBouncycastleAsn1SmimeSMIMECapability_initWithLibOrgBouncycastleAsn1ASN1Sequence_(LibOrgBouncycastleAsn1ASN1Sequence *seq) {
  J2OBJC_CREATE_IMPL(LibOrgBouncycastleAsn1SmimeSMIMECapability, initWithLibOrgBouncycastleAsn1ASN1Sequence_, seq)
}

void LibOrgBouncycastleAsn1SmimeSMIMECapability_initWithLibOrgBouncycastleAsn1ASN1ObjectIdentifier_withLibOrgBouncycastleAsn1ASN1Encodable_(LibOrgBouncycastleAsn1SmimeSMIMECapability *self, LibOrgBouncycastleAsn1ASN1ObjectIdentifier *capabilityID, id<LibOrgBouncycastleAsn1ASN1Encodable> parameters) {
  LibOrgBouncycastleAsn1ASN1Object_init(self);
  self->capabilityID_ = capabilityID;
  self->parameters_ = parameters;
}

LibOrgBouncycastleAsn1SmimeSMIMECapability *new_LibOrgBouncycastleAsn1SmimeSMIMECapability_initWithLibOrgBouncycastleAsn1ASN1ObjectIdentifier_withLibOrgBouncycastleAsn1ASN1Encodable_(LibOrgBouncycastleAsn1ASN1ObjectIdentifier *capabilityID, id<LibOrgBouncycastleAsn1ASN1Encodable> parameters) {
  J2OBJC_NEW_IMPL(LibOrgBouncycastleAsn1SmimeSMIMECapability, initWithLibOrgBouncycastleAsn1ASN1ObjectIdentifier_withLibOrgBouncycastleAsn1ASN1Encodable_, capabilityID, parameters)
}

LibOrgBouncycastleAsn1SmimeSMIMECapability *create_LibOrgBouncycastleAsn1SmimeSMIMECapability_initWithLibOrgBouncycastleAsn1ASN1ObjectIdentifier_withLibOrgBouncycastleAsn1ASN1Encodable_(LibOrgBouncycastleAsn1ASN1ObjectIdentifier *capabilityID, id<LibOrgBouncycastleAsn1ASN1Encodable> parameters) {
  J2OBJC_CREATE_IMPL(LibOrgBouncycastleAsn1SmimeSMIMECapability, initWithLibOrgBouncycastleAsn1ASN1ObjectIdentifier_withLibOrgBouncycastleAsn1ASN1Encodable_, capabilityID, parameters)
}

LibOrgBouncycastleAsn1SmimeSMIMECapability *LibOrgBouncycastleAsn1SmimeSMIMECapability_getInstanceWithId_(id obj) {
  LibOrgBouncycastleAsn1SmimeSMIMECapability_initialize();
  if (obj == nil || [obj isKindOfClass:[LibOrgBouncycastleAsn1SmimeSMIMECapability class]]) {
    return (LibOrgBouncycastleAsn1SmimeSMIMECapability *) cast_chk(obj, [LibOrgBouncycastleAsn1SmimeSMIMECapability class]);
  }
  if ([obj isKindOfClass:[LibOrgBouncycastleAsn1ASN1Sequence class]]) {
    return new_LibOrgBouncycastleAsn1SmimeSMIMECapability_initWithLibOrgBouncycastleAsn1ASN1Sequence_((LibOrgBouncycastleAsn1ASN1Sequence *) obj);
  }
  @throw new_JavaLangIllegalArgumentException_initWithNSString_(@"Invalid SMIMECapability");
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(LibOrgBouncycastleAsn1SmimeSMIMECapability)
