//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/asn1/x509/TargetInformation.java
//

#ifndef TargetInformation_H
#define TargetInformation_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "ASN1Object.h"
#include "J2ObjC_header.h"

@class IOSObjectArray;
@class LibOrgBouncycastleAsn1ASN1Primitive;
@class LibOrgBouncycastleAsn1X509Targets;

@interface LibOrgBouncycastleAsn1X509TargetInformation : LibOrgBouncycastleAsn1ASN1Object

#pragma mark Public

- (instancetype __nonnull)initWithLibOrgBouncycastleAsn1X509TargetArray:(IOSObjectArray *)targets;

- (instancetype __nonnull)initWithLibOrgBouncycastleAsn1X509Targets:(LibOrgBouncycastleAsn1X509Targets *)targets;

+ (LibOrgBouncycastleAsn1X509TargetInformation *)getInstanceWithId:(id)obj;

- (IOSObjectArray *)getTargetsObjects;

- (LibOrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(LibOrgBouncycastleAsn1X509TargetInformation)

FOUNDATION_EXPORT LibOrgBouncycastleAsn1X509TargetInformation *LibOrgBouncycastleAsn1X509TargetInformation_getInstanceWithId_(id obj);

FOUNDATION_EXPORT void LibOrgBouncycastleAsn1X509TargetInformation_initWithLibOrgBouncycastleAsn1X509Targets_(LibOrgBouncycastleAsn1X509TargetInformation *self, LibOrgBouncycastleAsn1X509Targets *targets);

FOUNDATION_EXPORT LibOrgBouncycastleAsn1X509TargetInformation *new_LibOrgBouncycastleAsn1X509TargetInformation_initWithLibOrgBouncycastleAsn1X509Targets_(LibOrgBouncycastleAsn1X509Targets *targets) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT LibOrgBouncycastleAsn1X509TargetInformation *create_LibOrgBouncycastleAsn1X509TargetInformation_initWithLibOrgBouncycastleAsn1X509Targets_(LibOrgBouncycastleAsn1X509Targets *targets);

FOUNDATION_EXPORT void LibOrgBouncycastleAsn1X509TargetInformation_initWithLibOrgBouncycastleAsn1X509TargetArray_(LibOrgBouncycastleAsn1X509TargetInformation *self, IOSObjectArray *targets);

FOUNDATION_EXPORT LibOrgBouncycastleAsn1X509TargetInformation *new_LibOrgBouncycastleAsn1X509TargetInformation_initWithLibOrgBouncycastleAsn1X509TargetArray_(IOSObjectArray *targets) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT LibOrgBouncycastleAsn1X509TargetInformation *create_LibOrgBouncycastleAsn1X509TargetInformation_initWithLibOrgBouncycastleAsn1X509TargetArray_(IOSObjectArray *targets);

J2OBJC_TYPE_LITERAL_HEADER(LibOrgBouncycastleAsn1X509TargetInformation)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // TargetInformation_H
