//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/pqc/asn1/XMSSMTKeyParams.java
//

#ifndef XMSSMTKeyParams_H
#define XMSSMTKeyParams_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "ASN1Object.h"
#include "J2ObjC_header.h"

@class LibOrgBouncycastleAsn1ASN1Primitive;
@class LibOrgBouncycastleAsn1X509AlgorithmIdentifier;

@interface LibOrgBouncycastlePqcAsn1XMSSMTKeyParams : LibOrgBouncycastleAsn1ASN1Object

#pragma mark Public

- (instancetype __nonnull)initWithInt:(jint)height
                              withInt:(jint)layers
withLibOrgBouncycastleAsn1X509AlgorithmIdentifier:(LibOrgBouncycastleAsn1X509AlgorithmIdentifier *)treeDigest;

- (jint)getHeight;

+ (LibOrgBouncycastlePqcAsn1XMSSMTKeyParams *)getInstanceWithId:(id)o;

- (jint)getLayers;

- (LibOrgBouncycastleAsn1X509AlgorithmIdentifier *)getTreeDigest;

- (LibOrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(LibOrgBouncycastlePqcAsn1XMSSMTKeyParams)

FOUNDATION_EXPORT void LibOrgBouncycastlePqcAsn1XMSSMTKeyParams_initWithInt_withInt_withLibOrgBouncycastleAsn1X509AlgorithmIdentifier_(LibOrgBouncycastlePqcAsn1XMSSMTKeyParams *self, jint height, jint layers, LibOrgBouncycastleAsn1X509AlgorithmIdentifier *treeDigest);

FOUNDATION_EXPORT LibOrgBouncycastlePqcAsn1XMSSMTKeyParams *new_LibOrgBouncycastlePqcAsn1XMSSMTKeyParams_initWithInt_withInt_withLibOrgBouncycastleAsn1X509AlgorithmIdentifier_(jint height, jint layers, LibOrgBouncycastleAsn1X509AlgorithmIdentifier *treeDigest) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT LibOrgBouncycastlePqcAsn1XMSSMTKeyParams *create_LibOrgBouncycastlePqcAsn1XMSSMTKeyParams_initWithInt_withInt_withLibOrgBouncycastleAsn1X509AlgorithmIdentifier_(jint height, jint layers, LibOrgBouncycastleAsn1X509AlgorithmIdentifier *treeDigest);

FOUNDATION_EXPORT LibOrgBouncycastlePqcAsn1XMSSMTKeyParams *LibOrgBouncycastlePqcAsn1XMSSMTKeyParams_getInstanceWithId_(id o);

J2OBJC_TYPE_LITERAL_HEADER(LibOrgBouncycastlePqcAsn1XMSSMTKeyParams)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // XMSSMTKeyParams_H
