//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/src/main/kotlin/lib/org/bouncycastle/pqc/jcajce/interfaces/XMSSMTKey.java
//

#include "J2ObjC_source.h"
#include "XMSSMTKey.h"

@interface LibOrgBouncycastlePqcJcajceInterfacesXMSSMTKey : NSObject

@end

@implementation LibOrgBouncycastlePqcJcajceInterfacesXMSSMTKey

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "I", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getHeight);
  methods[1].selector = @selector(getLayers);
  methods[2].selector = @selector(getTreeDigest);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _LibOrgBouncycastlePqcJcajceInterfacesXMSSMTKey = { "XMSSMTKey", "lib.org.bouncycastle.pqc.jcajce.interfaces", NULL, methods, NULL, 7, 0x609, 3, 0, -1, -1, -1, -1, -1 };
  return &_LibOrgBouncycastlePqcJcajceInterfacesXMSSMTKey;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(LibOrgBouncycastlePqcJcajceInterfacesXMSSMTKey)
